// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BillingStatus.
const (
	BillingStatusCancelled BillingStatus = "cancelled"
	BillingStatusCompleted BillingStatus = "completed"
	BillingStatusPending   BillingStatus = "pending"
	BillingStatusWaiting   BillingStatus = "waiting"
)

// Valid indicates whether the value is a known member of the BillingStatus enum.
func (e BillingStatus) Valid() bool {
	switch e {
	case BillingStatusCancelled:
		return true
	case BillingStatusCompleted:
		return true
	case BillingStatusPending:
		return true
	case BillingStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for CageCageSize.
const (
	CageCageSizeLarge  CageCageSize = "large"
	CageCageSizeMedium CageCageSize = "medium"
	CageCageSizeSmall  CageCageSize = "small"
)

// Valid indicates whether the value is a known member of the CageCageSize enum.
func (e CageCageSize) Valid() bool {
	switch e {
	case CageCageSizeLarge:
		return true
	case CageCageSizeMedium:
		return true
	case CageCageSizeSmall:
		return true
	default:
		return false
	}
}

// Defines values for CageCageType.
const (
	CageCageTypeCat     CageCageType = "cat"
	CageCageTypeDog     CageCageType = "dog"
	CageCageTypeGeneral CageCageType = "general"
	CageCageTypeIcu     CageCageType = "icu"
)

// Valid indicates whether the value is a known member of the CageCageType enum.
func (e CageCageType) Valid() bool {
	switch e {
	case CageCageTypeCat:
		return true
	case CageCageTypeDog:
		return true
	case CageCageTypeGeneral:
		return true
	case CageCageTypeIcu:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseCode.
const (
	CONFLICT        ErrorResponseCode = "CONFLICT"
	FORBIDDEN       ErrorResponseCode = "FORBIDDEN"
	INTERNALERROR   ErrorResponseCode = "INTERNAL_ERROR"
	NOTFOUND        ErrorResponseCode = "NOT_FOUND"
	UNAUTHORIZED    ErrorResponseCode = "UNAUTHORIZED"
	VALIDATIONERROR ErrorResponseCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case NOTFOUND:
		return true
	case UNAUTHORIZED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for ExaminationStatus.
const (
	ExaminationStatusEmpty ExaminationStatus = "依頼中"
	ExaminationStatusN1    ExaminationStatus = "検査中"
	ExaminationStatusN2    ExaminationStatus = "完了"
)

// Valid indicates whether the value is a known member of the ExaminationStatus enum.
func (e ExaminationStatus) Valid() bool {
	switch e {
	case ExaminationStatusEmpty:
		return true
	case ExaminationStatusN1:
		return true
	case ExaminationStatusN2:
		return true
	default:
		return false
	}
}

// Defines values for ExaminationItemStatus.
const (
	ExaminationItemStatusHigh   ExaminationItemStatus = "high"
	ExaminationItemStatusLow    ExaminationItemStatus = "low"
	ExaminationItemStatusNormal ExaminationItemStatus = "normal"
)

// Valid indicates whether the value is a known member of the ExaminationItemStatus enum.
func (e ExaminationItemStatus) Valid() bool {
	switch e {
	case ExaminationItemStatusHigh:
		return true
	case ExaminationItemStatusLow:
		return true
	case ExaminationItemStatusNormal:
		return true
	default:
		return false
	}
}

// Defines values for HospitalizationHospitalizationType.
const (
	HospitalizationHospitalizationTypeHospitalization HospitalizationHospitalizationType = "hospitalization"
	HospitalizationHospitalizationTypeHotel           HospitalizationHospitalizationType = "hotel"
)

// Valid indicates whether the value is a known member of the HospitalizationHospitalizationType enum.
func (e HospitalizationHospitalizationType) Valid() bool {
	switch e {
	case HospitalizationHospitalizationTypeHospitalization:
		return true
	case HospitalizationHospitalizationTypeHotel:
		return true
	default:
		return false
	}
}

// Defines values for HospitalizationStatus.
const (
	HospitalizationStatusAdmitted   HospitalizationStatus = "admitted"
	HospitalizationStatusDischarged HospitalizationStatus = "discharged"
	HospitalizationStatusReserved   HospitalizationStatus = "reserved"
)

// Valid indicates whether the value is a known member of the HospitalizationStatus enum.
func (e HospitalizationStatus) Valid() bool {
	switch e {
	case HospitalizationStatusAdmitted:
		return true
	case HospitalizationStatusDischarged:
		return true
	case HospitalizationStatusReserved:
		return true
	default:
		return false
	}
}

// Defines values for HospitalizationPlanBillingUnit.
const (
	PerDay   HospitalizationPlanBillingUnit = "per_day"
	PerNight HospitalizationPlanBillingUnit = "per_night"
)

// Valid indicates whether the value is a known member of the HospitalizationPlanBillingUnit enum.
func (e HospitalizationPlanBillingUnit) Valid() bool {
	switch e {
	case PerDay:
		return true
	case PerNight:
		return true
	default:
		return false
	}
}

// Defines values for HospitalizationPlanBodySize.
const (
	HospitalizationPlanBodySizeLarge  HospitalizationPlanBodySize = "large"
	HospitalizationPlanBodySizeMedium HospitalizationPlanBodySize = "medium"
	HospitalizationPlanBodySizeSmall  HospitalizationPlanBodySize = "small"
)

// Valid indicates whether the value is a known member of the HospitalizationPlanBodySize enum.
func (e HospitalizationPlanBodySize) Valid() bool {
	switch e {
	case HospitalizationPlanBodySizeLarge:
		return true
	case HospitalizationPlanBodySizeMedium:
		return true
	case HospitalizationPlanBodySizeSmall:
		return true
	default:
		return false
	}
}

// Defines values for InventoryItemCategory.
const (
	InventoryItemCategoryConsumable InventoryItemCategory = "consumable"
	InventoryItemCategoryFood       InventoryItemCategory = "food"
	InventoryItemCategoryMedicine   InventoryItemCategory = "medicine"
	InventoryItemCategoryOther      InventoryItemCategory = "other"
)

// Valid indicates whether the value is a known member of the InventoryItemCategory enum.
func (e InventoryItemCategory) Valid() bool {
	switch e {
	case InventoryItemCategoryConsumable:
		return true
	case InventoryItemCategoryFood:
		return true
	case InventoryItemCategoryMedicine:
		return true
	case InventoryItemCategoryOther:
		return true
	default:
		return false
	}
}

// Defines values for InventoryItemStatus.
const (
	InventoryItemStatusLow        InventoryItemStatus = "low"
	InventoryItemStatusOutOfStock InventoryItemStatus = "out_of_stock"
	InventoryItemStatusSufficient InventoryItemStatus = "sufficient"
)

// Valid indicates whether the value is a known member of the InventoryItemStatus enum.
func (e InventoryItemStatus) Valid() bool {
	switch e {
	case InventoryItemStatusLow:
		return true
	case InventoryItemStatusOutOfStock:
		return true
	case InventoryItemStatusSufficient:
		return true
	default:
		return false
	}
}

// Defines values for LoginResponseUserType.
const (
	LoginResponseUserTypeClinicAdmin LoginResponseUserType = "clinic_admin"
	LoginResponseUserTypeStaff       LoginResponseUserType = "staff"
	LoginResponseUserTypeSystemAdmin LoginResponseUserType = "system_admin"
)

// Valid indicates whether the value is a known member of the LoginResponseUserType enum.
func (e LoginResponseUserType) Valid() bool {
	switch e {
	case LoginResponseUserTypeClinicAdmin:
		return true
	case LoginResponseUserTypeStaff:
		return true
	case LoginResponseUserTypeSystemAdmin:
		return true
	default:
		return false
	}
}

// Defines values for MedicalRecordStatus.
const (
	Draft     MedicalRecordStatus = "draft"
	Finalized MedicalRecordStatus = "finalized"
)

// Valid indicates whether the value is a known member of the MedicalRecordStatus enum.
func (e MedicalRecordStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Finalized:
		return true
	default:
		return false
	}
}

// Defines values for MedicineDosageForm.
const (
	Injection MedicineDosageForm = "injection"
	Liquid    MedicineDosageForm = "liquid"
	Powder    MedicineDosageForm = "powder"
	Tablet    MedicineDosageForm = "tablet"
	Topical   MedicineDosageForm = "topical"
)

// Valid indicates whether the value is a known member of the MedicineDosageForm enum.
func (e MedicineDosageForm) Valid() bool {
	switch e {
	case Injection:
		return true
	case Liquid:
		return true
	case Powder:
		return true
	case Tablet:
		return true
	case Topical:
		return true
	default:
		return false
	}
}

// Defines values for MedicineMedicineUnit.
const (
	PerDose   MedicineMedicineUnit = "per_dose"
	PerGram   MedicineMedicineUnit = "per_gram"
	PerMl     MedicineMedicineUnit = "per_ml"
	PerTablet MedicineMedicineUnit = "per_tablet"
)

// Valid indicates whether the value is a known member of the MedicineMedicineUnit enum.
func (e MedicineMedicineUnit) Valid() bool {
	switch e {
	case PerDose:
		return true
	case PerGram:
		return true
	case PerMl:
		return true
	case PerTablet:
		return true
	default:
		return false
	}
}

// Defines values for OwnerMembershipType.
const (
	OwnerMembershipTypeDeceased    OwnerMembershipType = "deceased"
	OwnerMembershipTypeMember      OwnerMembershipType = "member"
	OwnerMembershipTypeNonMember   OwnerMembershipType = "non_member"
	OwnerMembershipTypeTransferred OwnerMembershipType = "transferred"
)

// Valid indicates whether the value is a known member of the OwnerMembershipType enum.
func (e OwnerMembershipType) Valid() bool {
	switch e {
	case OwnerMembershipTypeDeceased:
		return true
	case OwnerMembershipTypeMember:
		return true
	case OwnerMembershipTypeNonMember:
		return true
	case OwnerMembershipTypeTransferred:
		return true
	default:
		return false
	}
}

// Defines values for PetAcquisitionType.
const (
	PetAcquisitionTypeOther       PetAcquisitionType = "other"
	PetAcquisitionTypePurchased   PetAcquisitionType = "purchased"
	PetAcquisitionTypeRescued     PetAcquisitionType = "rescued"
	PetAcquisitionTypeTransferred PetAcquisitionType = "transferred"
)

// Valid indicates whether the value is a known member of the PetAcquisitionType enum.
func (e PetAcquisitionType) Valid() bool {
	switch e {
	case PetAcquisitionTypeOther:
		return true
	case PetAcquisitionTypePurchased:
		return true
	case PetAcquisitionTypeRescued:
		return true
	case PetAcquisitionTypeTransferred:
		return true
	default:
		return false
	}
}

// Defines values for PetDangerLevel.
const (
	High   PetDangerLevel = "high"
	Low    PetDangerLevel = "low"
	Medium PetDangerLevel = "medium"
)

// Valid indicates whether the value is a known member of the PetDangerLevel enum.
func (e PetDangerLevel) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for PetGender.
const (
	Female  PetGender = "female"
	Male    PetGender = "male"
	Unknown PetGender = "unknown"
)

// Valid indicates whether the value is a known member of the PetGender enum.
func (e PetGender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for PetStatus.
const (
	PetStatusAlive    PetStatus = "alive"
	PetStatusDeceased PetStatus = "deceased"
)

// Valid indicates whether the value is a known member of the PetStatus enum.
func (e PetStatus) Valid() bool {
	switch e {
	case PetStatusAlive:
		return true
	case PetStatusDeceased:
		return true
	default:
		return false
	}
}

// Defines values for ProcedureAnesthesia.
const (
	ProcedureAnesthesiaGeneral ProcedureAnesthesia = "general"
	ProcedureAnesthesiaLocal   ProcedureAnesthesia = "local"
	ProcedureAnesthesiaNone    ProcedureAnesthesia = "none"
)

// Valid indicates whether the value is a known member of the ProcedureAnesthesia enum.
func (e ProcedureAnesthesia) Valid() bool {
	switch e {
	case ProcedureAnesthesiaGeneral:
		return true
	case ProcedureAnesthesiaLocal:
		return true
	case ProcedureAnesthesiaNone:
		return true
	default:
		return false
	}
}

// Defines values for ReservationAppointmentStatus.
const (
	ReservationAppointmentStatusAccounting     ReservationAppointmentStatus = "accounting"
	ReservationAppointmentStatusCancelled      ReservationAppointmentStatus = "cancelled"
	ReservationAppointmentStatusCheckedIn      ReservationAppointmentStatus = "checked_in"
	ReservationAppointmentStatusCompleted      ReservationAppointmentStatus = "completed"
	ReservationAppointmentStatusConfirmed      ReservationAppointmentStatus = "confirmed"
	ReservationAppointmentStatusInConsultation ReservationAppointmentStatus = "in_consultation"
	ReservationAppointmentStatusPending        ReservationAppointmentStatus = "pending"
)

// Valid indicates whether the value is a known member of the ReservationAppointmentStatus enum.
func (e ReservationAppointmentStatus) Valid() bool {
	switch e {
	case ReservationAppointmentStatusAccounting:
		return true
	case ReservationAppointmentStatusCancelled:
		return true
	case ReservationAppointmentStatusCheckedIn:
		return true
	case ReservationAppointmentStatusCompleted:
		return true
	case ReservationAppointmentStatusConfirmed:
		return true
	case ReservationAppointmentStatusInConsultation:
		return true
	case ReservationAppointmentStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ReservationAppointmentVisitType.
const (
	First   ReservationAppointmentVisitType = "first"
	Revisit ReservationAppointmentVisitType = "revisit"
)

// Valid indicates whether the value is a known member of the ReservationAppointmentVisitType enum.
func (e ReservationAppointmentVisitType) Valid() bool {
	switch e {
	case First:
		return true
	case Revisit:
		return true
	default:
		return false
	}
}

// Defines values for StaffStaffRole.
const (
	StaffStaffRoleManager      StaffStaffRole = "manager"
	StaffStaffRoleNurse        StaffStaffRole = "nurse"
	StaffStaffRoleReception    StaffStaffRole = "reception"
	StaffStaffRoleTrimmer      StaffStaffRole = "trimmer"
	StaffStaffRoleVeterinarian StaffStaffRole = "veterinarian"
)

// Valid indicates whether the value is a known member of the StaffStaffRole enum.
func (e StaffStaffRole) Valid() bool {
	switch e {
	case StaffStaffRoleManager:
		return true
	case StaffStaffRoleNurse:
		return true
	case StaffStaffRoleReception:
		return true
	case StaffStaffRoleTrimmer:
		return true
	case StaffStaffRoleVeterinarian:
		return true
	default:
		return false
	}
}

// Defines values for StaffRegistrationRequestStaffRole.
const (
	StaffRegistrationRequestStaffRoleManager      StaffRegistrationRequestStaffRole = "manager"
	StaffRegistrationRequestStaffRoleNurse        StaffRegistrationRequestStaffRole = "nurse"
	StaffRegistrationRequestStaffRoleReception    StaffRegistrationRequestStaffRole = "reception"
	StaffRegistrationRequestStaffRoleTrimmer      StaffRegistrationRequestStaffRole = "trimmer"
	StaffRegistrationRequestStaffRoleVeterinarian StaffRegistrationRequestStaffRole = "veterinarian"
)

// Valid indicates whether the value is a known member of the StaffRegistrationRequestStaffRole enum.
func (e StaffRegistrationRequestStaffRole) Valid() bool {
	switch e {
	case StaffRegistrationRequestStaffRoleManager:
		return true
	case StaffRegistrationRequestStaffRoleNurse:
		return true
	case StaffRegistrationRequestStaffRoleReception:
		return true
	case StaffRegistrationRequestStaffRoleTrimmer:
		return true
	case StaffRegistrationRequestStaffRoleVeterinarian:
		return true
	default:
		return false
	}
}

// Defines values for TrimmingRecordBwUnit.
const (
	G  TrimmingRecordBwUnit = "g"
	Kg TrimmingRecordBwUnit = "Kg"
)

// Valid indicates whether the value is a known member of the TrimmingRecordBwUnit enum.
func (e TrimmingRecordBwUnit) Valid() bool {
	switch e {
	case G:
		return true
	case Kg:
		return true
	default:
		return false
	}
}

// Defines values for TrimmingRecordStatus.
const (
	TrimmingRecordStatusCompleted  TrimmingRecordStatus = "completed"
	TrimmingRecordStatusInProgress TrimmingRecordStatus = "in_progress"
	TrimmingRecordStatusReserved   TrimmingRecordStatus = "reserved"
)

// Valid indicates whether the value is a known member of the TrimmingRecordStatus enum.
func (e TrimmingRecordStatus) Valid() bool {
	switch e {
	case TrimmingRecordStatusCompleted:
		return true
	case TrimmingRecordStatusInProgress:
		return true
	case TrimmingRecordStatusReserved:
		return true
	default:
		return false
	}
}

// Defines values for VaccinationNextScheduleType.
const (
	N1year  VaccinationNextScheduleType = "1year"
	N3weeks VaccinationNextScheduleType = "3weeks"
	N4weeks VaccinationNextScheduleType = "4weeks"
	Other   VaccinationNextScheduleType = "other"
)

// Valid indicates whether the value is a known member of the VaccinationNextScheduleType enum.
func (e VaccinationNextScheduleType) Valid() bool {
	switch e {
	case N1year:
		return true
	case N3weeks:
		return true
	case N4weeks:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for VaccineSpecies.
const (
	VaccineSpeciesBoth VaccineSpecies = "both"
	VaccineSpeciesCat  VaccineSpecies = "cat"
	VaccineSpeciesDog  VaccineSpecies = "dog"
)

// Valid indicates whether the value is a known member of the VaccineSpecies enum.
func (e VaccineSpecies) Valid() bool {
	switch e {
	case VaccineSpeciesBoth:
		return true
	case VaccineSpeciesCat:
		return true
	case VaccineSpeciesDog:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountingsParamsStatus.
const (
	Cancelled ListAccountingsParamsStatus = "cancelled"
	Paid      ListAccountingsParamsStatus = "paid"
	Pending   ListAccountingsParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListAccountingsParamsStatus enum.
func (e ListAccountingsParamsStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Paid:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ListExaminationsParamsStatus.
const (
	ListExaminationsParamsStatusEmpty ListExaminationsParamsStatus = "依頼中"
	ListExaminationsParamsStatusN1    ListExaminationsParamsStatus = "検査中"
	ListExaminationsParamsStatusN2    ListExaminationsParamsStatus = "完了"
)

// Valid indicates whether the value is a known member of the ListExaminationsParamsStatus enum.
func (e ListExaminationsParamsStatus) Valid() bool {
	switch e {
	case ListExaminationsParamsStatusEmpty:
		return true
	case ListExaminationsParamsStatusN1:
		return true
	case ListExaminationsParamsStatusN2:
		return true
	default:
		return false
	}
}

// Defines values for ListInventoryParamsStatus.
const (
	Active   ListInventoryParamsStatus = "active"
	Inactive ListInventoryParamsStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ListInventoryParamsStatus enum.
func (e ListInventoryParamsStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// Defines values for ListCagesParamsCageType.
const (
	ListCagesParamsCageTypeCat     ListCagesParamsCageType = "cat"
	ListCagesParamsCageTypeDog     ListCagesParamsCageType = "dog"
	ListCagesParamsCageTypeGeneral ListCagesParamsCageType = "general"
	ListCagesParamsCageTypeIcu     ListCagesParamsCageType = "icu"
)

// Valid indicates whether the value is a known member of the ListCagesParamsCageType enum.
func (e ListCagesParamsCageType) Valid() bool {
	switch e {
	case ListCagesParamsCageTypeCat:
		return true
	case ListCagesParamsCageTypeDog:
		return true
	case ListCagesParamsCageTypeGeneral:
		return true
	case ListCagesParamsCageTypeIcu:
		return true
	default:
		return false
	}
}

// Defines values for ListVaccinesParamsSpecies.
const (
	Both ListVaccinesParamsSpecies = "both"
	Cat  ListVaccinesParamsSpecies = "cat"
	Dog  ListVaccinesParamsSpecies = "dog"
)

// Valid indicates whether the value is a known member of the ListVaccinesParamsSpecies enum.
func (e ListVaccinesParamsSpecies) Valid() bool {
	switch e {
	case Both:
		return true
	case Cat:
		return true
	case Dog:
		return true
	default:
		return false
	}
}

// AnimalSpecies defines model for AnimalSpecies.
type AnimalSpecies struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	IsActive  *bool               `json:"is_active,omitempty"`

	// Name 種別名（例：犬、猫）
	Name      string     `json:"name"`
	SortOrder *int       `json:"sort_order,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Billing defines model for Billing.
type Billing struct {
	ClinicId          *openapi_types.UUID `json:"clinic_id,omitempty"`
	CompletedAt       *time.Time          `json:"completed_at,omitempty"`
	CreatedAt         *time.Time          `json:"created_at,omitempty"`
	HasInsurance      *bool               `json:"has_insurance,omitempty"`
	HospitalizationId *openapi_types.UUID `json:"hospitalization_id,omitempty"`
	Id                *openapi_types.UUID `json:"id,omitempty"`
	MedicalRecordId   *openapi_types.UUID `json:"medical_record_id,omitempty"`
	Memo              *string             `json:"memo,omitempty"`
	OwnerId           *openapi_types.UUID `json:"owner_id,omitempty"`
	PetId             *openapi_types.UUID `json:"pet_id,omitempty"`
	ScheduledDate     openapi_types.Date  `json:"scheduled_date"`
	Status            *BillingStatus      `json:"status,omitempty"`
	Subtotal          *int                `json:"subtotal,omitempty"`
	TaxTotal          *int                `json:"tax_total,omitempty"`
	TotalAmount       *int                `json:"total_amount,omitempty"`
	UpdatedAt         *time.Time          `json:"updated_at,omitempty"`
}

// BillingStatus defines model for Billing.Status.
type BillingStatus string

// Cage defines model for Cage.
type Cage struct {
	CageSize    *CageCageSize       `json:"cage_size,omitempty"`
	CageType    *CageCageType       `json:"cage_type,omitempty"`
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	Price       *float64            `json:"price,omitempty"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// CageCageSize defines model for Cage.CageSize.
type CageCageSize string

// CageCageType defines model for Cage.CageType.
type CageCageType string

// CheckupType defines model for CheckupType.
type CheckupType struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Interval 推奨間隔
	Interval  *string  `json:"interval,omitempty"`
	IsActive  *bool    `json:"is_active,omitempty"`
	Name      string   `json:"name"`
	Price     *float64 `json:"price,omitempty"`
	SortOrder *int     `json:"sort_order,omitempty"`

	// TargetAge 対象年齢
	TargetAge *string    `json:"target_age,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Clinic defines model for Clinic.
type Clinic struct {
	Address            *string              `json:"address,omitempty"`
	CreatedAt          *time.Time           `json:"created_at,omitempty"`
	DirectorName       *string              `json:"director_name,omitempty"`
	Email              *openapi_types.Email `json:"email,omitempty"`
	FaxNumber          *string              `json:"fax_number,omitempty"`
	Id                 *openapi_types.UUID  `json:"id,omitempty"`
	IsActive           *bool                `json:"is_active,omitempty"`
	LogoUrl            *string              `json:"logo_url,omitempty"`
	Name               *string              `json:"name,omitempty"`
	PhoneNumber        *string              `json:"phone_number,omitempty"`
	PostalCode         *string              `json:"postal_code,omitempty"`
	RegistrationNumber *string              `json:"registration_number,omitempty"`
	UpdatedAt          *time.Time           `json:"updated_at,omitempty"`
	Website            *string              `json:"website,omitempty"`
}

// Consultation defines model for Consultation.
type Consultation struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`

	// Duration 所要時間（分）
	Duration      *int                `json:"duration,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsActive      *bool               `json:"is_active,omitempty"`
	Name          string              `json:"name"`
	Price         *float64            `json:"price,omitempty"`
	SortOrder     *int                `json:"sort_order,omitempty"`
	TimeCondition *string             `json:"time_condition,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// DiagnosisCategory defines model for DiagnosisCategory.
type DiagnosisCategory struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// DiagnosisName defines model for DiagnosisName.
type DiagnosisName struct {
	ClinicId            *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt           *time.Time          `json:"created_at,omitempty"`
	Description         *string             `json:"description,omitempty"`
	DiagnosisCategoryId openapi_types.UUID  `json:"diagnosis_category_id"`
	Id                  *openapi_types.UUID `json:"id,omitempty"`
	IsActive            *bool               `json:"is_active,omitempty"`
	Name                string              `json:"name"`
	SortOrder           *int                `json:"sort_order,omitempty"`
	UpdatedAt           *time.Time          `json:"updated_at,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code 機械可読なエラーコード
	Code ErrorResponseCode `json:"code"`

	// Details フィールドレベルのバリデーションエラー詳細
	Details *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"details,omitempty"`

	// Message 人間可読なエラーメッセージ
	Message string `json:"message"`
}

// ErrorResponseCode 機械可読なエラーコード
type ErrorResponseCode string

// Examination defines model for Examination.
type Examination struct {
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	Date            openapi_types.Date  `json:"date"`
	Doctor          *Staff              `json:"doctor,omitempty"`
	DoctorId        *openapi_types.UUID `json:"doctor_id,omitempty"`
	ExamType        *ExaminationType    `json:"exam_type,omitempty"`
	ExamTypeId      openapi_types.UUID  `json:"exam_type_id"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Items           *[]ExaminationItem  `json:"items,omitempty"`
	Machine         *string             `json:"machine,omitempty"`
	MedicalRecordId openapi_types.UUID  `json:"medical_record_id"`
	Pet             *Pet                `json:"pet,omitempty"`
	PetId           *openapi_types.UUID `json:"pet_id,omitempty"`
	ResultSummary   *string             `json:"result_summary,omitempty"`
	Status          *ExaminationStatus  `json:"status,omitempty"`
	UpdatedAt       *time.Time          `json:"updated_at,omitempty"`
}

// ExaminationStatus defines model for Examination.Status.
type ExaminationStatus string

// ExaminationItem defines model for ExaminationItem.
type ExaminationItem struct {
	CreatedAt       *time.Time             `json:"created_at,omitempty"`
	ExamId          *openapi_types.UUID    `json:"exam_id,omitempty"`
	Id              *openapi_types.UUID    `json:"id,omitempty"`
	InspectionValue *string                `json:"inspection_value,omitempty"`
	Name            *string                `json:"name,omitempty"`
	NormalValue     *string                `json:"normal_value,omitempty"`
	Ref             *string                `json:"ref,omitempty"`
	Result          *string                `json:"result,omitempty"`
	SortOrder       *int                   `json:"sort_order,omitempty"`
	Status          *ExaminationItemStatus `json:"status,omitempty"`
	Unit            *string                `json:"unit,omitempty"`
	UpdatedAt       *time.Time             `json:"updated_at,omitempty"`
}

// ExaminationItemStatus defines model for ExaminationItem.Status.
type ExaminationItemStatus string

// ExaminationType defines model for ExaminationType.
type ExaminationType struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	Price       *float64            `json:"price,omitempty"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// Hospitalization defines model for Hospitalization.
type Hospitalization struct {
	CageId              *openapi_types.UUID                `json:"cage_id,omitempty"`
	ClinicId            *openapi_types.UUID                `json:"clinic_id,omitempty"`
	CreatedAt           *time.Time                         `json:"created_at,omitempty"`
	DoctorId            *openapi_types.UUID                `json:"doctor_id,omitempty"`
	EndDate             openapi_types.Date                 `json:"end_date"`
	HospitalizationType HospitalizationHospitalizationType `json:"hospitalization_type"`
	Id                  *openapi_types.UUID                `json:"id,omitempty"`
	Memo                *string                            `json:"memo,omitempty"`
	OwnerId             openapi_types.UUID                 `json:"owner_id"`
	OwnerRequest        *string                            `json:"owner_request,omitempty"`
	PetId               openapi_types.UUID                 `json:"pet_id"`
	StaffNotes          *string                            `json:"staff_notes,omitempty"`
	StartDate           openapi_types.Date                 `json:"start_date"`
	Status              *HospitalizationStatus             `json:"status,omitempty"`
	UpdatedAt           *time.Time                         `json:"updated_at,omitempty"`
}

// HospitalizationHospitalizationType defines model for Hospitalization.HospitalizationType.
type HospitalizationHospitalizationType string

// HospitalizationStatus defines model for Hospitalization.Status.
type HospitalizationStatus string

// HospitalizationPlan defines model for HospitalizationPlan.
type HospitalizationPlan struct {
	BillingUnit *HospitalizationPlanBillingUnit `json:"billing_unit,omitempty"`
	BodySize    *HospitalizationPlanBodySize    `json:"body_size,omitempty"`
	ClinicId    *openapi_types.UUID             `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time                      `json:"created_at,omitempty"`
	Description *string                         `json:"description,omitempty"`
	Id          *openapi_types.UUID             `json:"id,omitempty"`
	IsActive    *bool                           `json:"is_active,omitempty"`
	Name        string                          `json:"name"`
	Price       *float64                        `json:"price,omitempty"`
	SortOrder   *int                            `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time                      `json:"updated_at,omitempty"`
}

// HospitalizationPlanBillingUnit defines model for HospitalizationPlan.BillingUnit.
type HospitalizationPlanBillingUnit string

// HospitalizationPlanBodySize defines model for HospitalizationPlan.BodySize.
type HospitalizationPlanBodySize string

// Insurance defines model for Insurance.
type Insurance struct {
	ClinicId     *openapi_types.UUID `json:"clinic_id,omitempty"`
	ContactPhone *string             `json:"contact_phone,omitempty"`
	CoverageRate *int                `json:"coverage_rate,omitempty"`
	CreatedAt    *time.Time          `json:"created_at,omitempty"`
	Description  *string             `json:"description,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	IsActive     *bool               `json:"is_active,omitempty"`
	Name         string              `json:"name"`
	SortOrder    *int                `json:"sort_order,omitempty"`
	UpdatedAt    *time.Time          `json:"updated_at,omitempty"`
}

// InventoryItem defines model for InventoryItem.
type InventoryItem struct {
	Category      InventoryItemCategory `json:"category"`
	ClinicId      *openapi_types.UUID   `json:"clinic_id,omitempty"`
	CreatedAt     *time.Time            `json:"created_at,omitempty"`
	ExpiryDate    *openapi_types.Date   `json:"expiry_date,omitempty"`
	Id            *openapi_types.UUID   `json:"id,omitempty"`
	LastRestocked *openapi_types.Date   `json:"last_restocked,omitempty"`
	Location      *string               `json:"location,omitempty"`
	MinStockLevel *int                  `json:"min_stock_level,omitempty"`
	Name          string                `json:"name"`
	Quantity      *int                  `json:"quantity,omitempty"`
	Status        *InventoryItemStatus  `json:"status,omitempty"`
	Supplier      *string               `json:"supplier,omitempty"`
	Unit          string                `json:"unit"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
}

// InventoryItemCategory defines model for InventoryItem.Category.
type InventoryItemCategory string

// InventoryItemStatus defines model for InventoryItem.Status.
type InventoryItemStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse ログイン成功レスポンス。JWTトークンは httpOnly Cookie (`auth_token`) でセットされるためボディには含まれない。
type LoginResponse struct {
	// ExpiresAt トークン有効期限（Unix timestamp）
	ExpiresAt *int64      `json:"expires_at,omitempty"`
	User      *MeResponse `json:"user,omitempty"`

	// UserType ユーザー種別
	UserType *LoginResponseUserType `json:"user_type,omitempty"`
}

// LoginResponseUserType ユーザー種別
type LoginResponseUserType string

// MeResponse defines model for MeResponse.
type MeResponse struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Clinics   *[]struct {
		ClinicId   *openapi_types.UUID `json:"clinic_id,omitempty"`
		ClinicName *string             `json:"clinic_name,omitempty"`
		IsMain     *bool               `json:"is_main,omitempty"`
	} `json:"clinics,omitempty"`
	DisplayName  *string              `json:"display_name,omitempty"`
	Email        *string              `json:"email,omitempty"`
	Id           *openapi_types.UUID  `json:"id,omitempty"`
	JobTitle     *string              `json:"job_title,omitempty"`
	MainClinicId *openapi_types.UUID  `json:"main_clinic_id,omitempty"`
	Permissions  *map[string][]string `json:"permissions,omitempty"`
	UserType     *string              `json:"user_type,omitempty"`
}

// MedicalRecord defines model for MedicalRecord.
type MedicalRecord struct {
	ClinicId  *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`

	// Date 診察日
	Date     openapi_types.Date  `json:"date"`
	DoctorId *openapi_types.UUID `json:"doctor_id,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	OwnerId  *openapi_types.UUID `json:"owner_id,omitempty"`
	PetId    *openapi_types.UUID `json:"pet_id,omitempty"`

	// RecordNo カルテ番号（自動採番）
	RecordNo                 string               `json:"record_no"`
	ReservationAppointmentId *openapi_types.UUID  `json:"reservation_appointment_id,omitempty"`
	Status                   *MedicalRecordStatus `json:"status,omitempty"`
	UpdatedAt                *time.Time           `json:"updated_at,omitempty"`
}

// MedicalRecordStatus defines model for MedicalRecord.Status.
type MedicalRecordStatus string

// Medicine defines model for Medicine.
type Medicine struct {
	ClinicId        *openapi_types.UUID   `json:"clinic_id,omitempty"`
	CreatedAt       *time.Time            `json:"created_at,omitempty"`
	DefaultQuantity *int                  `json:"default_quantity,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DosageForm      *MedicineDosageForm   `json:"dosage_form,omitempty"`
	Id              *openapi_types.UUID   `json:"id,omitempty"`
	InventoryId     *openapi_types.UUID   `json:"inventory_id,omitempty"`
	IsActive        *bool                 `json:"is_active,omitempty"`
	MedicineUnit    *MedicineMedicineUnit `json:"medicine_unit,omitempty"`
	Name            string                `json:"name"`
	Price           *float64              `json:"price,omitempty"`
	SortOrder       *int                  `json:"sort_order,omitempty"`
	UpdatedAt       *time.Time            `json:"updated_at,omitempty"`
}

// MedicineDosageForm defines model for Medicine.DosageForm.
type MedicineDosageForm string

// MedicineMedicineUnit defines model for Medicine.MedicineUnit.
type MedicineMedicineUnit string

// Owner defines model for Owner.
type Owner struct {
	Address1       *string              `json:"address1,omitempty"`
	Address2       *string              `json:"address2,omitempty"`
	BirthDate      *openapi_types.Date  `json:"birth_date,omitempty"`
	ClinicId       *openapi_types.UUID  `json:"clinic_id,omitempty"`
	Company        *string              `json:"company,omitempty"`
	CompanyPhone   *string              `json:"company_phone,omitempty"`
	CreatedAt      *time.Time           `json:"created_at,omitempty"`
	DiscountRate   *float64             `json:"discount_rate,omitempty"`
	Email          *openapi_types.Email `json:"email,omitempty"`
	HomeAddress1   *string              `json:"home_address1,omitempty"`
	HomeAddress2   *string              `json:"home_address2,omitempty"`
	HomePostalCode *string              `json:"home_postal_code,omitempty"`
	Id             *openapi_types.UUID  `json:"id,omitempty"`
	IsDangerous    *bool                `json:"is_dangerous,omitempty"`
	MembershipType *OwnerMembershipType `json:"membership_type,omitempty"`

	// OwnerName 飼主名（必須）
	OwnerName     string  `json:"owner_name"`
	OwnerNameKana *string `json:"owner_name_kana,omitempty"`

	// Pets ペット一覧（Preload時のみ含まれる）
	Pets       *[]Pet     `json:"pets,omitempty"`
	Phone      *string    `json:"phone,omitempty"`
	PostalCode *string    `json:"postal_code,omitempty"`
	Remarks    *string    `json:"remarks,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// OwnerMembershipType defines model for Owner.MembershipType.
type OwnerMembershipType string

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Data  []interface{} `json:"data"`
	Limit int           `json:"limit"`
	Page  int           `json:"page"`
	Total int           `json:"total"`
}

// Pet defines model for Pet.
type Pet struct {
	AcquisitionType *PetAcquisitionType `json:"acquisition_type,omitempty"`
	AnimalSpecies   *AnimalSpecies      `json:"animal_species,omitempty"`
	AnimalSpeciesId openapi_types.UUID  `json:"animal_species_id"`
	BirthDate       *openapi_types.Date `json:"birth_date,omitempty"`
	Breed           *string             `json:"breed,omitempty"`
	ClinicId        *openapi_types.UUID `json:"clinic_id,omitempty"`
	Color           *string             `json:"color,omitempty"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	DangerLevel     *PetDangerLevel     `json:"danger_level,omitempty"`
	Environment     *string             `json:"environment,omitempty"`
	Food            *string             `json:"food,omitempty"`
	Gender          *PetGender          `json:"gender,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Insurance       *Insurance          `json:"insurance,omitempty"`
	InsuranceId     *openapi_types.UUID `json:"insurance_id,omitempty"`
	LastVisit       *openapi_types.Date `json:"last_visit,omitempty"`

	// Name ペット名（必須）
	Name         string              `json:"name"`
	NeuteredDate *openapi_types.Date `json:"neutered_date,omitempty"`
	OwnerId      openapi_types.UUID  `json:"owner_id"`
	PetNameKana  *string             `json:"pet_name_kana,omitempty"`

	// PetNumber カルテ番号
	PetNumber *string    `json:"pet_number,omitempty"`
	Phone     *string    `json:"phone,omitempty"`
	Remarks   *string    `json:"remarks,omitempty"`
	Status    *PetStatus `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Weight    *float64   `json:"weight,omitempty"`
}

// PetAcquisitionType defines model for Pet.AcquisitionType.
type PetAcquisitionType string

// PetDangerLevel defines model for Pet.DangerLevel.
type PetDangerLevel string

// PetGender defines model for Pet.Gender.
type PetGender string

// PetStatus defines model for Pet.Status.
type PetStatus string

// Procedure defines model for Procedure.
type Procedure struct {
	Anesthesia  *ProcedureAnesthesia `json:"anesthesia,omitempty"`
	ClinicId    *openapi_types.UUID  `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	Description *string              `json:"description,omitempty"`
	Duration    *int                 `json:"duration,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	IsActive    *bool                `json:"is_active,omitempty"`
	Name        string               `json:"name"`
	Price       *float64             `json:"price,omitempty"`
	SortOrder   *int                 `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time           `json:"updated_at,omitempty"`
}

// ProcedureAnesthesia defines model for Procedure.Anesthesia.
type ProcedureAnesthesia string

// ReservationAppointment defines model for ReservationAppointment.
type ReservationAppointment struct {
	ClinicId  *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	DoctorId  *openapi_types.UUID `json:"doctor_id,omitempty"`

	// EndTime 終了日時
	EndTime       time.Time           `json:"end_time"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsDesignated  *bool               `json:"is_designated,omitempty"`
	Notes         *string             `json:"notes,omitempty"`
	OwnerId       *openapi_types.UUID `json:"owner_id,omitempty"`
	PetId         *openapi_types.UUID `json:"pet_id,omitempty"`
	ServiceTypeId openapi_types.UUID  `json:"service_type_id"`

	// StartTime 開始日時
	StartTime time.Time                        `json:"start_time"`
	Status    *ReservationAppointmentStatus    `json:"status,omitempty"`
	UpdatedAt *time.Time                       `json:"updated_at,omitempty"`
	VisitType *ReservationAppointmentVisitType `json:"visit_type,omitempty"`
}

// ReservationAppointmentStatus defines model for ReservationAppointment.Status.
type ReservationAppointmentStatus string

// ReservationAppointmentVisitType defines model for ReservationAppointment.VisitType.
type ReservationAppointmentVisitType string

// ServiceType defines model for ServiceType.
type ServiceType struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	Color       *string             `json:"color,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// Staff defines model for Staff.
type Staff struct {
	ClinicId      *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsActive      *bool               `json:"is_active,omitempty"`
	JobTitleId    *openapi_types.UUID `json:"job_title_id,omitempty"`
	LicenseNumber *string             `json:"license_number,omitempty"`
	Name          string              `json:"name"`
	SortOrder     *int                `json:"sort_order,omitempty"`
	StaffRole     StaffStaffRole      `json:"staff_role"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// StaffStaffRole defines model for Staff.StaffRole.
type StaffStaffRole string

// StaffRegistrationRequest スタッフ登録リクエスト。スタッフ情報とシステムアカウントをアトミックに作成する。clinic_id はJWTトークンから取得するためリクエストには含めない。
type StaffRegistrationRequest struct {
	// Email ログイン用メールアドレス（user_accounts に登録）
	Email openapi_types.Email `json:"email"`

	// JobTitleId 役職ID
	JobTitleId *openapi_types.UUID `json:"job_title_id,omitempty"`

	// LicenseNumber 獣医師免許番号等
	LicenseNumber *string `json:"license_number,omitempty"`

	// Name スタッフ氏名
	Name string `json:"name"`

	// Password 初期パスワード（8文字以上）
	Password string `json:"password"`

	// SortOrder 表示順
	SortOrder *int `json:"sort_order,omitempty"`

	// StaffCode スタッフコード
	StaffCode *string `json:"staff_code,omitempty"`

	// StaffRole 職種
	StaffRole StaffRegistrationRequestStaffRole `json:"staff_role"`
}

// StaffRegistrationRequestStaffRole 職種
type StaffRegistrationRequestStaffRole string

// TrimmingCourse defines model for TrimmingCourse.
type TrimmingCourse struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Duration    *string             `json:"duration,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	Price       *float64            `json:"price,omitempty"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	TargetSize  *string             `json:"target_size,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// TrimmingOption defines model for TrimmingOption.
type TrimmingOption struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	Combinable  *bool               `json:"combinable,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Duration    *string             `json:"duration,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	Price       *float64            `json:"price,omitempty"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// TrimmingRecord defines model for TrimmingRecord.
type TrimmingRecord struct {
	Bt             *string               `json:"bt,omitempty"`
	Bw             *string               `json:"bw,omitempty"`
	BwUnit         *TrimmingRecordBwUnit `json:"bw_unit,omitempty"`
	ClinicId       *openapi_types.UUID   `json:"clinic_id,omitempty"`
	CompletedImage *string               `json:"completed_image,omitempty"`
	CourseId       openapi_types.UUID    `json:"course_id"`
	CreatedAt      *time.Time            `json:"created_at,omitempty"`
	Date           openapi_types.Date    `json:"date"`
	Id             *openapi_types.UUID   `json:"id,omitempty"`
	PetId          *openapi_types.UUID   `json:"pet_id,omitempty"`
	Remarks        *string               `json:"remarks,omitempty"`
	StaffId        openapi_types.UUID    `json:"staff_id"`
	Status         *TrimmingRecordStatus `json:"status,omitempty"`
	StyleImage     *string               `json:"style_image,omitempty"`
	StyleRequest   *string               `json:"style_request,omitempty"`
	UpdatedAt      *time.Time            `json:"updated_at,omitempty"`
	UsedRibbon     *string               `json:"used_ribbon,omitempty"`
	UsedShampoo    *string               `json:"used_shampoo,omitempty"`
	Weight         *string               `json:"weight,omitempty"`
}

// TrimmingRecordBwUnit defines model for TrimmingRecord.BwUnit.
type TrimmingRecordBwUnit string

// TrimmingRecordStatus defines model for TrimmingRecord.Status.
type TrimmingRecordStatus string

// Vaccination defines model for Vaccination.
type Vaccination struct {
	CreatedAt        *time.Time                   `json:"created_at,omitempty"`
	Date             openapi_types.Date           `json:"date"`
	Doctor           *Staff                       `json:"doctor,omitempty"`
	DoctorId         *openapi_types.UUID          `json:"doctor_id,omitempty"`
	Id               *openapi_types.UUID          `json:"id,omitempty"`
	Lot1             *string                      `json:"lot1,omitempty"`
	Lot2             *string                      `json:"lot2,omitempty"`
	Lot3             *string                      `json:"lot3,omitempty"`
	Lot4             *string                      `json:"lot4,omitempty"`
	MedicalRecordId  openapi_types.UUID           `json:"medical_record_id"`
	NextDate         *openapi_types.Date          `json:"next_date,omitempty"`
	NextScheduleType *VaccinationNextScheduleType `json:"next_schedule_type,omitempty"`
	Pet              *Pet                         `json:"pet,omitempty"`
	PetId            *openapi_types.UUID          `json:"pet_id,omitempty"`
	Remarks          *string                      `json:"remarks,omitempty"`
	Supplemental     *bool                        `json:"supplemental,omitempty"`
	UpdatedAt        *time.Time                   `json:"updated_at,omitempty"`
	Vaccine          *Vaccine                     `json:"vaccine,omitempty"`
	VaccineId        openapi_types.UUID           `json:"vaccine_id"`
}

// VaccinationNextScheduleType defines model for Vaccination.NextScheduleType.
type VaccinationNextScheduleType string

// Vaccine defines model for Vaccine.
type Vaccine struct {
	ClinicId    *openapi_types.UUID `json:"clinic_id,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Interval    *string             `json:"interval,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        string              `json:"name"`
	Price       *float64            `json:"price,omitempty"`
	SortOrder   *int                `json:"sort_order,omitempty"`
	Species     *VaccineSpecies     `json:"species,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// VaccineSpecies defines model for Vaccine.Species.
type VaccineSpecies string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListAccountingsParams defines parameters for ListAccountings.
type ListAccountingsParams struct {
	Page   *int                         `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Status *ListAccountingsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListAccountingsParamsStatus defines parameters for ListAccountings.
type ListAccountingsParamsStatus string

// ListExaminationsParams defines parameters for ListExaminations.
type ListExaminationsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`

	// Status ステータスで絞り込み
	Status *ListExaminationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListExaminationsParamsStatus defines parameters for ListExaminations.
type ListExaminationsParamsStatus string

// ListHospitalizationsParams defines parameters for ListHospitalizations.
type ListHospitalizationsParams struct {
	Page   *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListInventoryParams defines parameters for ListInventory.
type ListInventoryParams struct {
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`

	// Status ステータスでフィルタリング
	Status *ListInventoryParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListInventoryParamsStatus defines parameters for ListInventory.
type ListInventoryParamsStatus string

// ListCagesParams defines parameters for ListCages.
type ListCagesParams struct {
	// CageType ケージ種別でフィルタリング
	CageType *ListCagesParamsCageType `form:"cage_type,omitempty" json:"cage_type,omitempty"`
}

// ListCagesParamsCageType defines parameters for ListCages.
type ListCagesParamsCageType string

// ListDiagnosisNamesParams defines parameters for ListDiagnosisNames.
type ListDiagnosisNamesParams struct {
	CategoryId *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// ListStaffsParams defines parameters for ListStaffs.
type ListStaffsParams struct {
	Role *string `form:"role,omitempty" json:"role,omitempty"`
}

// ListVaccinesParams defines parameters for ListVaccines.
type ListVaccinesParams struct {
	// Species 対象種でフィルタリング
	Species *ListVaccinesParamsSpecies `form:"species,omitempty" json:"species,omitempty"`
}

// ListVaccinesParamsSpecies defines parameters for ListVaccines.
type ListVaccinesParamsSpecies string

// ListMedicalRecordsParams defines parameters for ListMedicalRecords.
type ListMedicalRecordsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListOwnersParams defines parameters for ListOwners.
type ListOwnersParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Search 飼主名・かな・電話番号などで部分一致検索
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListPetsParams defines parameters for ListPets.
type ListPetsParams struct {
	Page   *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListReservationsParams defines parameters for ListReservations.
type ListReservationsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Date 日付フィルター (YYYY-MM-DD)
	Date   *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
	Status *string             `form:"status,omitempty" json:"status,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListTrimmingsParams defines parameters for ListTrimmings.
type ListTrimmingsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// ListVaccinationsParams defines parameters for ListVaccinations.
type ListVaccinationsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// PetId ペットIDで絞り込み
	PetId *openapi_types.UUID `form:"pet_id,omitempty" json:"pet_id,omitempty"`

	// OwnerId 飼主IDで絞り込み
	OwnerId *openapi_types.UUID `form:"owner_id,omitempty" json:"owner_id,omitempty"`
}

// CreateAccountingJSONRequestBody defines body for CreateAccounting for application/json ContentType.
type CreateAccountingJSONRequestBody = Billing

// UpdateAccountingJSONRequestBody defines body for UpdateAccounting for application/json ContentType.
type UpdateAccountingJSONRequestBody = Billing

// UpdateClinicJSONRequestBody defines body for UpdateClinic for application/json ContentType.
type UpdateClinicJSONRequestBody = Clinic

// UpdateCompanyJSONRequestBody defines body for UpdateCompany for application/json ContentType.
type UpdateCompanyJSONRequestBody = Clinic

// CreateExaminationJSONRequestBody defines body for CreateExamination for application/json ContentType.
type CreateExaminationJSONRequestBody = Examination

// UpdateExaminationJSONRequestBody defines body for UpdateExamination for application/json ContentType.
type UpdateExaminationJSONRequestBody = Examination

// CreateHospitalizationJSONRequestBody defines body for CreateHospitalization for application/json ContentType.
type CreateHospitalizationJSONRequestBody = Hospitalization

// UpdateHospitalizationJSONRequestBody defines body for UpdateHospitalization for application/json ContentType.
type UpdateHospitalizationJSONRequestBody = Hospitalization

// CreateInventoryItemJSONRequestBody defines body for CreateInventoryItem for application/json ContentType.
type CreateInventoryItemJSONRequestBody = InventoryItem

// UpdateInventoryItemJSONRequestBody defines body for UpdateInventoryItem for application/json ContentType.
type UpdateInventoryItemJSONRequestBody = InventoryItem

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateCageJSONRequestBody defines body for CreateCage for application/json ContentType.
type CreateCageJSONRequestBody = Cage

// UpdateCageJSONRequestBody defines body for UpdateCage for application/json ContentType.
type UpdateCageJSONRequestBody = Cage

// CreateCheckupTypeJSONRequestBody defines body for CreateCheckupType for application/json ContentType.
type CreateCheckupTypeJSONRequestBody = CheckupType

// UpdateCheckupTypeJSONRequestBody defines body for UpdateCheckupType for application/json ContentType.
type UpdateCheckupTypeJSONRequestBody = CheckupType

// CreateConsultationJSONRequestBody defines body for CreateConsultation for application/json ContentType.
type CreateConsultationJSONRequestBody = Consultation

// UpdateConsultationJSONRequestBody defines body for UpdateConsultation for application/json ContentType.
type UpdateConsultationJSONRequestBody = Consultation

// CreateDiagnosisCategoryJSONRequestBody defines body for CreateDiagnosisCategory for application/json ContentType.
type CreateDiagnosisCategoryJSONRequestBody = DiagnosisCategory

// UpdateDiagnosisCategoryJSONRequestBody defines body for UpdateDiagnosisCategory for application/json ContentType.
type UpdateDiagnosisCategoryJSONRequestBody = DiagnosisCategory

// CreateDiagnosisNameJSONRequestBody defines body for CreateDiagnosisName for application/json ContentType.
type CreateDiagnosisNameJSONRequestBody = DiagnosisName

// UpdateDiagnosisNameJSONRequestBody defines body for UpdateDiagnosisName for application/json ContentType.
type UpdateDiagnosisNameJSONRequestBody = DiagnosisName

// CreateExaminationTypeJSONRequestBody defines body for CreateExaminationType for application/json ContentType.
type CreateExaminationTypeJSONRequestBody = ExaminationType

// UpdateExaminationTypeJSONRequestBody defines body for UpdateExaminationType for application/json ContentType.
type UpdateExaminationTypeJSONRequestBody = ExaminationType

// CreateHospitalizationPlanJSONRequestBody defines body for CreateHospitalizationPlan for application/json ContentType.
type CreateHospitalizationPlanJSONRequestBody = HospitalizationPlan

// UpdateHospitalizationPlanJSONRequestBody defines body for UpdateHospitalizationPlan for application/json ContentType.
type UpdateHospitalizationPlanJSONRequestBody = HospitalizationPlan

// CreateInsuranceJSONRequestBody defines body for CreateInsurance for application/json ContentType.
type CreateInsuranceJSONRequestBody = Insurance

// UpdateInsuranceJSONRequestBody defines body for UpdateInsurance for application/json ContentType.
type UpdateInsuranceJSONRequestBody = Insurance

// CreateMedicineJSONRequestBody defines body for CreateMedicine for application/json ContentType.
type CreateMedicineJSONRequestBody = Medicine

// UpdateMedicineJSONRequestBody defines body for UpdateMedicine for application/json ContentType.
type UpdateMedicineJSONRequestBody = Medicine

// CreateProcedureJSONRequestBody defines body for CreateProcedure for application/json ContentType.
type CreateProcedureJSONRequestBody = Procedure

// UpdateProcedureJSONRequestBody defines body for UpdateProcedure for application/json ContentType.
type UpdateProcedureJSONRequestBody = Procedure

// CreateServiceTypeJSONRequestBody defines body for CreateServiceType for application/json ContentType.
type CreateServiceTypeJSONRequestBody = ServiceType

// UpdateServiceTypeJSONRequestBody defines body for UpdateServiceType for application/json ContentType.
type UpdateServiceTypeJSONRequestBody = ServiceType

// CreateStaffJSONRequestBody defines body for CreateStaff for application/json ContentType.
type CreateStaffJSONRequestBody = StaffRegistrationRequest

// UpdateStaffJSONRequestBody defines body for UpdateStaff for application/json ContentType.
type UpdateStaffJSONRequestBody = Staff

// CreateTrimmingCourseJSONRequestBody defines body for CreateTrimmingCourse for application/json ContentType.
type CreateTrimmingCourseJSONRequestBody = TrimmingCourse

// UpdateTrimmingCourseJSONRequestBody defines body for UpdateTrimmingCourse for application/json ContentType.
type UpdateTrimmingCourseJSONRequestBody = TrimmingCourse

// CreateTrimmingOptionJSONRequestBody defines body for CreateTrimmingOption for application/json ContentType.
type CreateTrimmingOptionJSONRequestBody = TrimmingOption

// UpdateTrimmingOptionJSONRequestBody defines body for UpdateTrimmingOption for application/json ContentType.
type UpdateTrimmingOptionJSONRequestBody = TrimmingOption

// CreateVaccineJSONRequestBody defines body for CreateVaccine for application/json ContentType.
type CreateVaccineJSONRequestBody = Vaccine

// UpdateVaccineJSONRequestBody defines body for UpdateVaccine for application/json ContentType.
type UpdateVaccineJSONRequestBody = Vaccine

// CreateMedicalRecordJSONRequestBody defines body for CreateMedicalRecord for application/json ContentType.
type CreateMedicalRecordJSONRequestBody = MedicalRecord

// UpdateMedicalRecordJSONRequestBody defines body for UpdateMedicalRecord for application/json ContentType.
type UpdateMedicalRecordJSONRequestBody = MedicalRecord

// CreateOwnerJSONRequestBody defines body for CreateOwner for application/json ContentType.
type CreateOwnerJSONRequestBody = Owner

// UpdateOwnerJSONRequestBody defines body for UpdateOwner for application/json ContentType.
type UpdateOwnerJSONRequestBody = Owner

// CreatePetJSONRequestBody defines body for CreatePet for application/json ContentType.
type CreatePetJSONRequestBody = Pet

// UpdatePetJSONRequestBody defines body for UpdatePet for application/json ContentType.
type UpdatePetJSONRequestBody = Pet

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = ReservationAppointment

// UpdateReservationJSONRequestBody defines body for UpdateReservation for application/json ContentType.
type UpdateReservationJSONRequestBody = ReservationAppointment

// CreateTrimmingJSONRequestBody defines body for CreateTrimming for application/json ContentType.
type CreateTrimmingJSONRequestBody = TrimmingRecord

// UpdateTrimmingJSONRequestBody defines body for UpdateTrimming for application/json ContentType.
type UpdateTrimmingJSONRequestBody = TrimmingRecord

// CreateVaccinationJSONRequestBody defines body for CreateVaccination for application/json ContentType.
type CreateVaccinationJSONRequestBody = Vaccination

// UpdateVaccinationJSONRequestBody defines body for UpdateVaccination for application/json ContentType.
type UpdateVaccinationJSONRequestBody = Vaccination
