
FROM node:24-alpine

RUN apk add --no-cache tzdata && npm install -g pnpm@9

ENV TZ=Asia/Tokyo

WORKDIR /app

COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["pnpm", "dev"]
