FROM golang:1.25-alpine

WORKDIR /app

# ホットリロード用ツール
RUN go install github.com/air-verse/air@latest

COPY go.mod ./
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["./entrypoint.sh"]
