import { paths } from "@/config/paths";
import { ICON } from "@/lib/design-tokens";
import type { MenuItem } from "@/types";
import {
  ResourceAccounting,
  ResourceAccountingReports,
  ResourceCashRegisterClose,
  ResourceCheckups,
  ResourceClosingSettings,
  ResourceExaminations,
  ResourceHospitalSettings,
  ResourceHospitalization,
  ResourceIdentityLinks,
  ResourceInventory,
  ResourceLabImport,
  ResourceLstepAnalytics,
  ResourceMasterAnimalSpecies,
  ResourceMasterHospitalization as ResourceMasterHosp,
  ResourceMasterInsurance,
  ResourceMasterMedical,
  ResourceMasterMerchandise,
  ResourceMasterPermission,
  ResourceMasterReservationType,
  ResourceMasterStaff,
  ResourceMasterTrimming as ResourceMasterTrim,
  ResourceMedicalRecords,
  ResourceOwners,
  ResourcePaymentMethod,
  ResourceReception,
  ResourceReservations,
  ResourceShifts,
  ResourceTrimming,
  ResourceVaccinations,
} from "@/types/generated/models";
import {
  Activity,
  BarChart3,
  Bed,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardSignature,
  CreditCard,
  FileText,
  FlaskConical,
  HelpCircle,
  History,
  LayoutDashboard,
  Link2,
  Lock,
  MessageSquare,
  MessageSquareText,
  Package,
  PawPrint,
  Pill,
  Scissors,
  Settings,
  ShieldCheck,
  Smartphone,
  Syringe,
  Tag,
  TestTube,
  Users,
} from "lucide-react";

export interface SidebarMenuSection {
  title: string;
  items: MenuItem[];
}

export const sidebarMenuSections: SidebarMenuSection[] = [
  {
    title: "診療業務",
    items: [
      { icon: <LayoutDashboard className={ICON.toolbar} />, label: "当日の受付", path: paths.home.getHref(), resource: ResourceReception },
      { icon: <Users className={ICON.toolbar} />, label: "飼主・ペット", path: paths.owners.getHref(), resource: ResourceOwners },
      { icon: <Calendar className={ICON.toolbar} />, label: "予約管理", path: paths.reservations.getHref(), resource: ResourceReservations },
      { icon: <FileText className={ICON.toolbar} />, label: "カルテ", path: paths.medicalRecords.getHref(), resource: ResourceMedicalRecords },
      { icon: <TestTube className={ICON.toolbar} />, label: "検査管理", path: paths.examinations.getHref(), resource: ResourceExaminations },
      { icon: <TestTube className={ICON.toolbar} />, label: "検査受信", path: paths.labDevice.getHref(), resource: ResourceLabImport },
      { icon: <Scissors className={ICON.toolbar} />, label: "トリミング", path: paths.trimming.getHref(), resource: ResourceTrimming },
      { icon: <Syringe className={ICON.toolbar} />, label: "予防接種", path: paths.vaccinations.getHref(), resource: ResourceVaccinations },
      { icon: <ClipboardCheck className={ICON.toolbar} />, label: "定期健診", path: paths.checkups.getHref(), resource: ResourceCheckups },
    ],
  },
  {
    title: "運用・管理",
    items: [
      { icon: <CreditCard className={ICON.toolbar} />, label: "会計管理", path: paths.accounting.getHref(), resource: ResourceAccounting },
      { icon: <CreditCard className={ICON.toolbar} />, label: "レジ締め", path: paths.accounting.close.getHref(), resource: ResourceCashRegisterClose },
      { icon: <History className={ICON.toolbar} />, label: "締め履歴", path: paths.accounting.closeHistory.getHref(), resource: ResourceCashRegisterClose },
      { icon: <BarChart3 className={ICON.toolbar} />, label: "月次集計レポート", path: paths.accounting.reports.getHref(), resource: ResourceAccountingReports },
      { icon: <Bed className={ICON.toolbar} />, label: "入院・ホテル", path: paths.hospitalization.getHref(), resource: ResourceHospitalization },
      { icon: <Package className={ICON.toolbar} />, label: "在庫管理", path: paths.inventory.getHref(), resource: ResourceInventory },
      { icon: <CalendarDays className={ICON.toolbar} />, label: "シフト管理", path: paths.shifts.getHref(), resource: ResourceShifts },
      { icon: <BarChart3 className={ICON.toolbar} />, label: "集計・分析", path: paths.aggregation.getHref(), resource: ResourceOwners },
    ],
  },
  {
    title: "LINE予約管理",
    items: [
      {
        icon: <Smartphone className={ICON.toolbar} />,
        label: "LINE予約管理",
        path: paths.lineReservation.getHref(),
        resource: ResourceReservations,
        subItems: [
          { label: "基本設定", path: paths.lineReservation.settings.getHref(), resource: ResourceReservations },
          { label: "ページ編集", path: paths.lineReservation.pageEditor.getHref(), resource: ResourceReservations },
          { label: "予約枠", path: paths.lineReservation.slots.getHref(), resource: ResourceMasterReservationType },
        ],
      },
    ],
  },
  {
    title: "Lステップ連携",
    items: [
      {
        icon: <MessageSquare className={ICON.toolbar} />,
        label: "Lステップ連携",
        path: paths.lstep.settings.getHref(),
        resource: ResourceHospitalSettings,
        subItems: [
          { icon: <MessageSquare className={ICON.toolbar} />, label: "連携設定", path: paths.lstep.settings.getHref(), resource: ResourceHospitalSettings },
          { icon: <Tag className={ICON.toolbar} />, label: "タグ管理", path: paths.lstep.tags.getHref(), resource: ResourceLstepAnalytics },
          { icon: <ClipboardSignature className={ICON.toolbar} />, label: "健診対象者抽出", path: paths.lstep.checkupSync.getHref(), resource: ResourceHospitalSettings },
          { icon: <BarChart3 className={ICON.toolbar} />, label: "分析レポート", path: paths.lstep.analytics.getHref(), resource: ResourceLstepAnalytics },
          { icon: <Activity className={ICON.toolbar} />, label: "配信監視", path: paths.lstep.deliveryMonitor.getHref(), resource: ResourceLstepAnalytics },
        ],
      },
    ],
  },
  {
    title: "システム設定",
    items: [
      {
        icon: <Settings className={ICON.toolbar} />,
        label: "マスタ設定",
        path: paths.settings.getHref(),
        subItems: [
          { icon: <Building2 className={ICON.toolbar} />, label: "医院", path: paths.settings.clinic.getHref(), resource: ResourceHospitalSettings },
          { icon: <PawPrint className={ICON.toolbar} />, label: "動物種類", path: paths.settings.animalSpecies.getHref(), resource: ResourceMasterAnimalSpecies },
          {
            icon: <FileText className={ICON.toolbar} />,
            label: "カルテ関連",
            resource: ResourceMasterMedical,
            subItems: [
              { icon: <ClipboardList className={ICON.toolbar} />, label: "診療項目", path: paths.settings.treatmentItems.getHref(), resource: ResourceMasterMedical },
              { icon: <Clipboard className={ICON.toolbar} />, label: "診断マスタ", path: paths.settings.diagnosis.getHref(), resource: ResourceMasterMedical },
              { icon: <ClipboardCheck className={ICON.toolbar} />, label: "問診設定", path: paths.settings.inquiryTemplates.getHref(), resource: ResourceMasterMedical },
              { icon: <MessageSquareText className={ICON.toolbar} />, label: "主訴カテゴリ", path: paths.settings.interview.chiefComplaint.getHref(), resource: ResourceMasterMedical },
              { icon: <Pill className={ICON.toolbar} />, label: "薬剤マスタ", path: paths.settings.medicine.getHref(), resource: ResourceMasterMedical },
              { icon: <TestTube className={ICON.toolbar} />, label: "検査マスタ", path: paths.settings.examination.getHref(), resource: ResourceMasterMedical },
              { icon: <FlaskConical className={ICON.toolbar} />, label: "検査機器マスタ", path: paths.settings.labDeviceItemMasters.getHref(), resource: ResourceLabImport },
            ],
          },
          { icon: <Activity className={ICON.toolbar} />, label: "予約区分", path: paths.settings.reservationType.getHref(), resource: ResourceMasterReservationType },
          {
            icon: <Bed className={ICON.toolbar} />,
            label: "入院・ケージ",
            resource: ResourceMasterHosp,
            subItems: [
              { icon: <Bed className={ICON.toolbar} />, label: "入院マスタ", path: paths.settings.hospitalization.getHref(), resource: ResourceMasterHosp },
              { icon: <Bed className={ICON.toolbar} />, label: "ケージマスタ", path: paths.settings.cage.getHref(), resource: ResourceMasterHosp },
            ],
          },
          {
            icon: <Scissors className={ICON.toolbar} />,
            label: "トリミング",
            resource: ResourceMasterTrim,
            subItems: [
              { icon: <Scissors className={ICON.toolbar} />, label: "トリミングマスタ", path: paths.settings.trimming.getHref(), resource: ResourceMasterTrim },
              { icon: <Scissors className={ICON.toolbar} />, label: "コース種別マスタ", path: paths.settings.trimmingCourseType.getHref(), resource: ResourceMasterTrim },
            ],
          },
          { icon: <Lock className={ICON.toolbar} />, label: "権限グループ", path: paths.settings.permissionGroups.getHref(), resource: ResourceMasterPermission },
          { icon: <Briefcase className={ICON.toolbar} />, label: "職種マスタ", path: paths.settings.occupations.getHref(), resource: ResourceMasterStaff },
          { icon: <Users className={ICON.toolbar} />, label: "スタッフ管理", path: paths.settings.staff.getHref(), resource: ResourceMasterStaff },
          { icon: <ShieldCheck className={ICON.toolbar} />, label: "保険マスタ", path: paths.settings.insurance.getHref(), resource: ResourceMasterInsurance },
          { icon: <Package className={ICON.toolbar} />, label: "物販・フード", path: paths.settings.merchandiseItems.getHref(), resource: ResourceMasterMerchandise },
          { icon: <CreditCard className={ICON.toolbar} />, label: "支払方法", path: paths.settings.paymentMethods.getHref(), resource: ResourcePaymentMethod },
          { icon: <Tag className={ICON.toolbar} />, label: "割引キャンペーン", path: paths.settings.campaigns.getHref(), resource: ResourceAccounting },
          { icon: <CalendarDays className={ICON.toolbar} />, label: "締め時間設定", path: paths.settings.closingTime.getHref(), resource: ResourceClosingSettings },
          { icon: <Calendar className={ICON.toolbar} />, label: "シフトテンプレート", path: paths.settings.shiftTemplates.getHref(), resource: ResourceShifts },
        ],
      },
      { icon: <Link2 className={ICON.toolbar} />, label: "同一飼主・ペット連携", path: paths.identityLinks.getHref(), resource: ResourceIdentityLinks },
    ],
  },
  {
    title: "ヘルプ",
    items: [{ icon: <HelpCircle className={ICON.toolbar} />, label: "取扱説明書", path: paths.manual.getHref() }],
  },
];
