-- 007_add_bank_transfer_payment_method.sql
-- Issue #127: payment_method ENUM に 'bank_transfer'（銀行振込）を追加する。
--
-- 背景: 新クリニック作成トリガー（001_init.sql）は payment_methods マスタへ
-- '銀行振込' を自動挿入する一方、payment_method ENUM は
-- ('cash', 'credit_card', 'electronic_money') の 3 値のみで「銀行振込」を表現できず、
-- 会計 payment_splits.method に保存できなかった（マスタと ENUM の不整合 = 本 Issue の実害源）。
--
-- 本 migration は ENUM 値の追加のみを行う緊急パッチである。
-- マスタ二重管理（payment_method_id 主軸化）の解消は #128 のスコープであり、ここでは扱わない。
--
-- 【安全性に関する注意（CRITICAL）】
-- migration runner（cmd/migrate）は各 .sql ファイルを単一トランザクションで実行する。
-- PostgreSQL 12+ ではトランザクション内 ALTER TYPE ... ADD VALUE は許可されるが、
-- 追加した ENUM 値を同一トランザクション内で利用することはできない
-- （"unsafe use of new value" エラーになる）。
-- したがって本ファイルには ADD VALUE 文のみを置き、'bank_transfer' を参照する
-- INSERT / UPDATE 等を絶対に混在させないこと。
--
-- ADD VALUE は不可逆（容易に DROP できない）だが、新規ファイル追記であり
-- 適用済み migration の checksum は破壊しないため、通常デプロイで適用される（db_reset 不要）。

ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'bank_transfer';
