-- Migration 007: idx_shift_entries_staff_date 削除
--
-- 削除理由:
--   shift_entries テーブルには以下の 2 つの一意制約が存在していた:
--
--     (A) uk_shift_staff_date UNIQUE (clinic_id, staff_id, date)  -- テーブル定義の制約
--     (B) idx_shift_entries_staff_date UNIQUE (staff_id, date)    -- グローバル一意制約 (本 migration で削除)
--
--   (B) は「スタッフが同日に複数クリニックでシフトを持てない」という過剰な制約を課していた。
--   しかしシステムは staff_clinic_assignments テーブルで複数クリニック所属を明示的にサポートし、
--   is_main フラグによる主所属管理が実装されている。
--
--   多拠点チェーン動物病院では、獣医師が午前・午後で複数院を掛け持ちするケースが想定される。
--   (A) がクリニック単位の一意性を保証しており、(B) は設計上の重複かつ過剰制約である。
--
--   migration 006 で "要 PO 判断" として保留されていた件。
--   DB 設計原則（アーキテクチャ上の multi-clinic サポートと制約の整合）に基づき削除する。
--
-- 影響範囲:
--   - reservation_schedule_repository.go の FindAllByDate / Save は
--     Scopes(clinicScope(clinicID)) + WHERE staff_id+date で検索しており、
--     (A) で十分カバーされる。(B) の削除は repository 動作に影響しない。
--   - 同日同クリニック内のシフト重複は引き続き (A) により防がれる。

DROP INDEX IF EXISTS idx_shift_entries_staff_date;
