import type { InventoryItem } from "@/types";

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "1",
    name: "フィラリア予防薬（小型犬用）",
    category: "medicine",
    quantity: 45,
    unit: "錠",
    minStockLevel: 20,
    location: "薬品棚A-1",
    expiryDate: "2027/03/15",
    supplier: "動物医薬品株式会社",
    lastRestocked: "2025/12/01",
    status: "sufficient",
  },
  {
    id: "2",
    name: "抗生物質（アモキシシリン）",
    category: "medicine",
    quantity: 8,
    unit: "本",
    minStockLevel: 10,
    location: "薬品棚A-2",
    expiryDate: "2026/06/30",
    supplier: "動物医薬品株式会社",
    lastRestocked: "2025/11/15",
    status: "low",
  },
  {
    id: "3",
    name: "注射器（5ml）",
    category: "consumable",
    quantity: 200,
    unit: "本",
    minStockLevel: 50,
    location: "消耗品棚B-1",
    supplier: "医療機器サプライ",
    lastRestocked: "2025/12/20",
    status: "sufficient",
  },
  {
    id: "4",
    name: "滅菌ガーゼ",
    category: "consumable",
    quantity: 0,
    unit: "パック",
    minStockLevel: 30,
    location: "消耗品棚B-2",
    supplier: "医療機器サプライ",
    lastRestocked: "2025/10/05",
    status: "out_of_stock",
  },
  {
    id: "5",
    name: "療法食（腎臓ケア）",
    category: "food",
    quantity: 25,
    unit: "袋",
    minStockLevel: 10,
    location: "フード棚C-1",
    expiryDate: "2026/08/01",
    supplier: "ペットフード販売",
    lastRestocked: "2025/12/10",
    status: "sufficient",
  },
  {
    id: "6",
    name: "療法食（消化器ケア）",
    category: "food",
    quantity: 5,
    unit: "袋",
    minStockLevel: 10,
    location: "フード棚C-2",
    expiryDate: "2026/05/15",
    supplier: "ペットフード販売",
    lastRestocked: "2025/11/25",
    status: "low",
  },
  {
    id: "7",
    name: "エリザベスカラー（Mサイズ）",
    category: "other",
    quantity: 12,
    unit: "個",
    minStockLevel: 5,
    location: "備品棚D-1",
    supplier: "ペット用品卸売",
    lastRestocked: "2025/09/20",
    status: "sufficient",
  },
  {
    id: "8",
    name: "点滴セット",
    category: "consumable",
    quantity: 15,
    unit: "セット",
    minStockLevel: 20,
    location: "消耗品棚B-3",
    supplier: "医療機器サプライ",
    lastRestocked: "2025/12/05",
    status: "low",
  },
];
