import type { ColumnData } from "@/types";

/** 開発用モックデータ: APIが空を返す場合のフォールバック */
export const MOCK_DASHBOARD_COLUMNS: ColumnData[] = [
  {
    title: "受付予約",
    appointments: [
      {
        id: "mock-1",
        time: "10:25",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-2",
        time: "10:55",
        ownerName: "佐藤 花子",
        petType: "猫",
        petName: "レオ",
        petId: "mock-pet-2",
        visitType: "初診",
        serviceType: "診療",
        isDesignated: false,
        doctor: "医師B",
      },
    ],
  },
  {
    title: "受付済",
    appointments: [
      {
        id: "mock-3",
        time: "10:30",
        ownerName: "田中　花子(タナカ　ハナコ)",
        petType: "猫",
        petName: "ミケ",
        petId: "mock-pet-3",
        visitType: "初診",
        serviceType: "診療",
        isDesignated: false,
        doctor: "医師B",
      },
      {
        id: "mock-4",
        time: "10:45",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Max(マックス)",
        petId: "mock-pet-4",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-5",
        time: "11:00",
        ownerName: "鈴木 一郎",
        petType: "犬",
        petName: "タロウ",
        petId: "mock-pet-5",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-6",
        time: "11:15",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: false,
        doctor: "医師C",
      },
      {
        id: "mock-7",
        time: "15:00",
        ownerName: "田中 美咲",
        petType: "犬",
        petName: "チョコ",
        petId: "mock-pet-6",
        visitType: "再診",
        serviceType: "トリミング",
        isDesignated: true,
        doctor: "スタッフA",
      },
      {
        id: "mock-8",
        time: "12:00",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "入院",
        isDesignated: false,
        doctor: "医師B",
      },
    ],
  },
  {
    title: "診療中",
    appointments: [
      {
        id: "mock-9",
        time: "10:00",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-10",
        time: "10:15",
        ownerName: "鈴木 一郎",
        petType: "犬",
        petName: "ジロウ",
        petId: "mock-pet-7",
        visitType: "初診",
        serviceType: "診療",
        isDesignated: false,
        doctor: "医師C",
      },
      {
        id: "mock-11",
        time: "10:20",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Max(マックス)",
        petId: "mock-pet-4",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師B",
      },
      {
        id: "mock-12",
        time: "10:10",
        ownerName: "山田 太郎",
        petType: "犬",
        petName: "ケン",
        petId: "mock-pet-8",
        visitType: "再診",
        serviceType: "診療",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-13",
        time: "10:25",
        ownerName: "高橋 由美",
        petType: "猫",
        petName: "ソラ",
        petId: "mock-pet-9",
        visitType: "初診",
        serviceType: "診療",
        isDesignated: false,
        doctor: "医師B",
      },
    ],
  },
  {
    title: "会計待ち",
    appointments: [
      {
        id: "mock-14",
        time: "09:45",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "診療",
        nextAppointment: "精算未確認",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-15",
        time: "09:50",
        ownerName: "田中　花子(タナカ　ハナコ)",
        petType: "猫",
        petName: "ミケ",
        petId: "mock-pet-3",
        visitType: "初診",
        serviceType: "診療",
        nextAppointment: "精算確認済",
        isDesignated: false,
        doctor: "医師C",
      },
      {
        id: "mock-16",
        time: "09:30",
        ownerName: "田中 美咲",
        petType: "犬",
        petName: "チョコ",
        petId: "mock-pet-6",
        visitType: "再診",
        serviceType: "トリミング",
        nextAppointment: "精算未確認",
        isDesignated: true,
        doctor: "スタッフA",
      },
      {
        id: "mock-17",
        time: "09:55",
        ownerName: "吉田 誠",
        petType: "犬",
        petName: "シロ",
        petId: "mock-pet-10",
        visitType: "再診",
        serviceType: "診療",
        nextAppointment: "精算確認済",
        isDesignated: true,
        doctor: "医師B",
      },
      {
        id: "mock-18",
        time: "10:05",
        ownerName: "井上 京子",
        petType: "猫",
        petName: "トラ",
        petId: "mock-pet-11",
        visitType: "初診",
        serviceType: "診療",
        nextAppointment: "精算未確認",
        isDesignated: false,
        doctor: "医師C",
      },
    ],
  },
  {
    title: "会計済",
    appointments: [
      {
        id: "mock-19",
        time: "09:00",
        ownerName: "林　文明(ハヤシ　フミアキ)",
        petType: "犬",
        petName: "Iris(イリス)",
        petId: "mock-pet-1",
        visitType: "再診",
        serviceType: "診療",
        nextAppointment: "次回予約無",
        isDesignated: true,
        doctor: "医師A",
      },
      {
        id: "mock-20",
        time: "09:15",
        ownerName: "佐々木 亮",
        petType: "猫",
        petName: "チビ",
        petId: "mock-pet-12",
        visitType: "再診",
        serviceType: "診療",
        nextAppointment: "次回予約済",
        isDesignated: false,
        doctor: "医師B",
      },
    ],
  },
];
