#!/usr/bin/env bash
# Refresh <!-- AUTO:* --> sections in .claude/CLAUDE.md from on-disk layout.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
CLAUDE="$ROOT/.claude/CLAUDE.md"
TMP=$(mktemp)

# architecture-dirs: keep curated rows; verify listed CLAUDE.md paths exist.
python3 - "$CLAUDE" <<'PY'
from pathlib import Path
import re, sys
claude = Path(sys.argv[1])
text = claude.read_text()
root = claude.parent.parent
rows = [
    ("backend/", "Go/Gin公式ベースライン、security invariant、Docker verification"),
    ("backend/migrations/", "Migration naming, clinic_id, CASCADE DELETE禁止"),
    ("frontend/", "React 19 patterns, design tokens, build commands"),
    ("frontend/src/features/", "Feature Indexing, index.ts structure"),
    ("frontend/src/hooks/", "Shared global hooks — placement rules, React hook rules"),
    ("infra/", "Infra-specific agent rules (`infra/CLAUDE.md`)"),
]
missing = [d for d, _ in rows if not (root / d / "CLAUDE.md").exists()]
if missing:
    raise SystemExit(f"AUTO architecture-dirs drift: missing CLAUDE.md under {missing}")
table = ["| Directory | Rules |", "|-----------|-------|"]
table += [f"| `{d}` | {r} |" for d, r in rows]
block = "<!-- AUTO:architecture-dirs -->\n" + "\n".join(table) + "\n<!-- AUTO:END:architecture-dirs -->"
text2, n = re.subn(
    r"<!-- AUTO:architecture-dirs -->.*?<!-- AUTO:END:architecture-dirs -->",
    block,
    text,
    count=1,
    flags=re.S,
)
if n != 1:
    raise SystemExit("architecture-dirs AUTO markers not found exactly once")
# commands-matrix: stamp only (human table above markers is source)
stamp = (
    "<!-- AUTO:commands-matrix -->\n"
    "<!-- Regenerated by scripts/generate-agent-doc-sections.sh — markers present; "
    f"verified {__import__('datetime').date.today().isoformat()}. -->\n"
    "<!-- AUTO:END:commands-matrix -->"
)
text2, n = re.subn(
    r"<!-- AUTO:commands-matrix -->.*?<!-- AUTO:END:commands-matrix -->",
    stamp,
    text2,
    count=1,
    flags=re.S,
)
if n != 1:
    raise SystemExit("commands-matrix AUTO markers not found exactly once")
claude.write_text(text2)
print("updated", claude)
PY
