import { Hospitalization, MedicalRecord, ReservationAppointment, TrimmingRecord, ColumnData, Pet, ExaminationRecord, AccountingRecord, VaccinationRecord, MasterItem } from "../types";

export const INITIAL_DASHBOARD_COLUMNS: ColumnData[] = [
    {
      title: "受付予約",
      appointments: [
        {
          id: "1",
          time: "10:25",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "1-2",
          time: "10:55",
          ownerName: "佐藤 花子",
          petType: "猫",
          petName: "レオ",
          petId: "p7",
          visitType: "初診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師B",
        },
      ],
    },
    {
      title: "受付済",
      appointments: [
        {
          id: "2",
          time: "10:30",
          ownerName: "田中　花子(タナカ　ハナコ)",
          petType: "猫",
          petName: "ミケ",
          petId: "3",
          visitType: "��診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師B",
        },
        {
          id: "3",
          time: "10:45",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Max(マックス)",
          petId: "2",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "4",
          time: "11:00",
          ownerName: "鈴木 一郎",
          petType: "犬",
          petName: "タロウ",
          petId: "p4",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "5",
          time: "11:15",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "6",
          time: "15:00",
          ownerName: "田中 美咲",
          petType: "犬",
          petName: "チョコ",
          petId: "p6",
          visitType: "再診",
          serviceType: "トリミング",
          isDesignated: true,
          doctor: "スタッフA",
        },
        {
          id: "7",
          time: "12:00",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "入院",
          isDesignated: false,
          doctor: "医師B",
        },
        {
          id: "2-2",
          time: "10:40",
          ownerName: "山本 健太",
          petType: "犬",
          petName: "ポチ",
          petId: "p19",
          visitType: "初診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "3-2",
          time: "11:10",
          ownerName: "佐藤 花子",
          petType: "猫",
          petName: "レオ",
          petId: "p7",
          visitType: "再診",
          serviceType: "ワクチン",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "4-2",
          time: "11:20",
          ownerName: "伊藤 次郎",
          petType: "犬",
          petName: "ハチ",
          petId: "p8",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師B",
        },
        {
          id: "5-2",
          time: "11:45",
          ownerName: "小林 さくら",
          petType: "猫",
          petName: "モモ",
          petId: "p9",
          visitType: "初診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "6-2",
          time: "12:15",
          ownerName: "中村 勇気",
          petType: "犬",
          petName: "ロッキー",
          petId: "p10",
          visitType: "再診",
          serviceType: "トリミング",
          isDesignated: true,
          doctor: "スタッフB",
        },
        {
          id: "7-2",
          time: "12:30",
          ownerName: "加藤 恵",
          petType: "猫",
          petName: "ルナ",
          petId: "p11",
          visitType: "再診",
          serviceType: "入院",
          isDesignated: false,
          doctor: "医師A",
        },
      ],
    },
    {
      title: "診療中",
      appointments: [
        {
          id: "8",
          time: "10:00",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "9",
          time: "10:15",
          ownerName: "鈴木 一郎",
          petType: "犬",
          petName: "ジロウ",
          petId: "p5",
          visitType: "初診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "10",
          time: "10:20",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Max(マックス)",
          petId: "2",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師B",
        },
        {
          id: "8-2",
          time: "10:10",
          ownerName: "山田 太郎",
          petType: "犬",
          petName: "ケン",
          petId: "p12",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "9-2",
          time: "10:25",
          ownerName: "高橋 由美",
          petType: "猫",
          petName: "ソラ",
          petId: "p13",
          visitType: "初診",
          serviceType: "診療",
          isDesignated: false,
          doctor: "医師B",
        },
        {
          id: "10-2",
          time: "10:35",
          ownerName: "松本 隆",
          petType: "犬",
          petName: "ゴン",
          petId: "p14",
          visitType: "再診",
          serviceType: "診療",
          isDesignated: true,
          doctor: "医師C",
        },
      ],
    },
    {
      title: "会計待ち",
      appointments: [
        {
          id: "12",
          time: "09:45",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "診療",
          nextAppointment: "精算未確認",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "13",
          time: "09:50",
          ownerName: "田中　花子(タナカ　ハナコ)",
          petType: "猫",
          petName: "ミケ",
          petId: "3",
          visitType: "初診",
          serviceType: "診療",
          nextAppointment: "精算確認済",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "14",
          time: "09:30",
          ownerName: "田中 美咲",
          petType: "犬",
          petName: "チョコ",
          petId: "p6",
          visitType: "再診",
          serviceType: "トリミング",
          nextAppointment: "精算未確認",
          isDesignated: true,
          doctor: "スタッフA",
        },
        {
          id: "12-2",
          time: "09:55",
          ownerName: "吉田 誠",
          petType: "犬",
          petName: "シロ",
          petId: "p15",
          visitType: "再診",
          serviceType: "診療",
          nextAppointment: "精算確認済",
          isDesignated: true,
          doctor: "医師B",
        },
        {
          id: "13-2",
          time: "10:05",
          ownerName: "井上 京子",
          petType: "猫",
          petName: "トラ",
          petId: "p16",
          visitType: "初診",
          serviceType: "診療",
          nextAppointment: "精算未確認",
          isDesignated: false,
          doctor: "医師C",
        },
        {
          id: "14-2",
          time: "11:40",
          ownerName: "木村 拓也",
          petType: "犬",
          petName: "ベロ",
          petId: "p17",
          visitType: "再診",
          serviceType: "トリミング",
          nextAppointment: "精算確認済",
          isDesignated: true,
          doctor: "スタッフB",
        },
      ],
    },
    {
      title: "会計済",
      appointments: [
        {
          id: "16",
          time: "09:00",
          ownerName: "林　文明(ハヤシ　フミアキ)",
          petType: "犬",
          petName: "Iris(イリス)",
          petId: "1",
          visitType: "再診",
          serviceType: "診療",
          nextAppointment: "次回予約無",
          isDesignated: true,
          doctor: "医師A",
        },
        {
          id: "16-2",
          time: "09:15",
          ownerName: "佐々木 亮",
          petType: "猫",
          petName: "チビ",
          petId: "p18",
          visitType: "再診",
          serviceType: "診療",
          nextAppointment: "次回予約済",
          isDesignated: false,
          doctor: "医師B",
        },
      ],
    },
  ];

export const MOCK_MEDICAL_RECORDS: MedicalRecord[] = [
    // --- 2025 History ---
    {
      id: "2",
      recordNo: "M-2025-089",
      date: "2025/12/20",
      ownerId: "30043",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petId: "3",
      petName: "ミケ",
      species: "猫",
      chiefComplaint: "定期検診、ワクチン接種",
      doctor: "医師B",
      status: "確定済",
    },
    {
      id: "3",
      recordNo: "M-2025-045",
      date: "2025/11/15",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "2",
      petName: "Max(マックス)",
      species: "犬",
      chiefComplaint: "右足の跛行",
      doctor: "医師A",
      status: "確定済",
    },
    {
      id: "4",
      recordNo: "M-2025-032",
      date: "2025/10/08",
      ownerId: "o4",
      ownerName: "田中 美咲",
      petId: "p6",
      petName: "チョコ",
      species: "犬",
      chiefComplaint: "皮膚の痒み",
      doctor: "医師C",
      status: "確定済",
    },
    // --- 2026/01/06 Today (Sorted by Time) ---
    // 09:00 Iris (Rec 21)
    {
      id: "21",
      recordNo: "M-2026-001",
      date: "2026/01/06 09:00",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "薬の処方",
      doctor: "医師A",
      status: "確定済",
    },
    // 09:15 Chibi (Rec 15)
    {
      id: "15",
      recordNo: "M-2026-002",
      date: "2026/01/06 09:15",
      ownerId: "o16",
      ownerName: "佐々木 亮",
      petId: "p18",
      petName: "チビ",
      species: "猫",
      chiefComplaint: "ワクチン接種",
      doctor: "医師B",
      status: "確定済",
    },
    // 09:30 Choco (Rec 11) - MOVED from 11:30
    {
      id: "11",
      recordNo: "M-2026-003",
      date: "2026/01/06 09:30",
      ownerId: "o4",
      ownerName: "田中 美咲",
      petId: "p6",
      petName: "チョコ",
      species: "犬",
      chiefComplaint: "トリミング後の皮膚チェック",
      doctor: "スタッフA",
      status: "確定済",
    },
    // 09:45 Iris (Rec 20)
    {
      id: "20",
      recordNo: "M-2026-004",
      date: "2026/01/06 09:45",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "再診（経過観察）",
      doctor: "医師A",
      status: "確定済",
    },
    // 09:50 Mike (Rec 10)
    {
      id: "10",
      recordNo: "M-2026-005",
      date: "2026/01/06 09:50",
      ownerId: "30043",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petId: "3",
      petName: "ミケ",
      species: "猫",
      chiefComplaint: "健康診断・ワクチン接種",
      doctor: "医師C",
      status: "確定済",
    },
    // 09:55 Shiro (Rec 12)
    {
      id: "12",
      recordNo: "M-2026-006",
      date: "2026/01/06 09:55",
      ownerId: "o13",
      ownerName: "吉田 誠",
      petId: "p15",
      petName: "シロ",
      species: "犬",
      chiefComplaint: "定期検診（爪切り含む）",
      doctor: "医師B",
      status: "確定済",
    },
    // 10:00 Iris (Rec 1)
    {
      id: "1",
      recordNo: "M-2026-007",
      date: "2026/01/06 10:00",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "食欲不振、嘔吐が続く",
      doctor: "医師A",
      status: "作成中",
    },
    // 10:05 Tora (Rec 13)
    {
      id: "13",
      recordNo: "M-2026-008",
      date: "2026/01/06 10:05",
      ownerId: "o14",
      ownerName: "井上 京子",
      petId: "p16",
      petName: "トラ",
      species: "猫",
      chiefComplaint: "血液検査（目やに）",
      doctor: "医師C",
      status: "確定済",
    },
    // 10:10 Ken (Rec 7)
    {
      id: "7",
      recordNo: "M-2026-009",
      date: "2026/01/06 10:10",
      ownerId: "o10",
      ownerName: "山田 太郎",
      petId: "p12",
      petName: "ケン",
      species: "犬",
      chiefComplaint: "耳を痒がる",
      doctor: "医師A",
      status: "作成中",
    },
    // 10:15 Jiro (Rec 5)
    {
      id: "5",
      recordNo: "M-2026-010",
      date: "2026/01/06 10:15",
      ownerId: "o3",
      ownerName: "鈴木 一郎",
      petId: "p5",
      petName: "ジロウ",
      species: "犬",
      chiefComplaint: "下痢",
      doctor: "医師C",
      status: "作成中",
    },
    // 10:20 Max (Rec 6)
    {
      id: "6",
      recordNo: "M-2026-011",
      date: "2026/01/06 10:20",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "2",
      petName: "Max(マックス)",
      species: "犬",
      chiefComplaint: "定期検診",
      doctor: "医師B",
      status: "作成中",
    },
    // 10:25 Sora (Rec 8)
    {
      id: "8",
      recordNo: "M-2026-012",
      date: "2026/01/06 10:25",
      ownerId: "o11",
      ownerName: "高橋 由美",
      petId: "p13",
      petName: "ソラ",
      species: "猫",
      chiefComplaint: "食欲不振",
      doctor: "医師B",
      status: "作成中",
    },
    // 10:25 Iris (Rec 30) - Reservation
    {
      id: "30",
      recordNo: "M-2026-013",
      date: "2026/01/06 10:25",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "予約診療",
      doctor: "医師A",
      status: "作成中",
    },
    // 10:30 Mike (Rec 22) - Microchip
    {
      id: "22",
      recordNo: "M-2026-014",
      date: "2026/01/06 10:30",
      ownerId: "30043",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petId: "3",
      petName: "ミケ",
      species: "猫",
      chiefComplaint: "マイクロチップ装着",
      doctor: "医師B",
      status: "作成中",
    },
    // 10:35 Gon (Rec 9)
    {
      id: "9",
      recordNo: "M-2026-015",
      date: "2026/01/06 10:35",
      ownerId: "o12",
      ownerName: "松本 隆",
      petId: "p14",
      petName: "ゴン",
      species: "犬",
      chiefComplaint: "足を引きずる",
      doctor: "医師C",
      status: "作成中",
    },
    // 10:40 Pochi (Rec 25)
    {
      id: "25",
      recordNo: "M-2026-016",
      date: "2026/01/06 10:40",
      ownerId: "o17",
      ownerName: "山本 健太",
      petId: "p19",
      petName: "ポチ",
      species: "犬",
      chiefComplaint: "ワクチン接種",
      doctor: "医師C",
      status: "作成中",
    },
    // 10:45 Max (Rec 28) - Nail Trim
    {
      id: "28",
      recordNo: "M-2026-017",
      date: "2026/01/06 10:45",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "2",
      petName: "Max(マックス)",
      species: "犬",
      chiefComplaint: "爪切り",
      doctor: "医師A",
      status: "作成中",
    },
    // 10:55 Leo (Rec 31)
    {
      id: "31",
      recordNo: "M-2026-018",
      date: "2026/01/06 10:55",
      ownerId: "o5",
      ownerName: "佐藤 花子",
      petId: "p7",
      petName: "レオ",
      species: "猫",
      chiefComplaint: "初診予約",
      doctor: "医師B",
      status: "作成中",
    },
    // 11:00 Taro (Rec 24)
    {
      id: "24",
      recordNo: "M-2026-019",
      date: "2026/01/06 11:00",
      ownerId: "o3",
      ownerName: "鈴木 一郎",
      petId: "p4",
      petName: "タロウ",
      species: "犬",
      chiefComplaint: "皮膚チェック",
      doctor: "医師A",
      status: "作成中",
    },
    // 11:10 Leo (Rec 17)
    {
      id: "17",
      recordNo: "M-2026-020",
      date: "2026/01/06 11:10",
      ownerId: "o5",
      ownerName: "佐藤 花子",
      petId: "p7",
      petName: "レオ",
      species: "猫",
      chiefComplaint: "ワクチン予約",
      doctor: "医師A",
      status: "作成中",
    },
    // 11:15 Iris (Rec 29)
    {
      id: "29",
      recordNo: "M-2026-021",
      date: "2026/01/06 11:15",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "経過観察（受付済）",
      doctor: "医師C",
      status: "作成中",
    },
    // 11:20 Hachi (Rec 26)
    {
      id: "26",
      recordNo: "M-2026-022",
      date: "2026/01/06 11:20",
      ownerId: "o6",
      ownerName: "伊藤 次郎",
      petId: "p8",
      petName: "ハチ",
      species: "犬",
      chiefComplaint: "健康診断",
      doctor: "医師B",
      status: "作成中",
    },
    // 11:40 Bero (Rec 14)
    {
      id: "14",
      recordNo: "M-2026-023",
      date: "2026/01/06 11:40",
      ownerId: "o15",
      ownerName: "木村 拓也",
      petId: "p17",
      petName: "ベロ",
      species: "犬",
      chiefComplaint: "グルーミング（爪切り・耳掃除）",
      doctor: "スタッフB",
      status: "確定済",
    },
    // 11:45 Momo (Rec 27)
    {
      id: "27",
      recordNo: "M-2026-024",
      date: "2026/01/06 11:45",
      ownerId: "o7",
      ownerName: "小林 さくら",
      petId: "p9",
      petName: "モモ",
      species: "猫",
      chiefComplaint: "目の充血",
      doctor: "医師C",
      status: "作成中",
    },
    // 12:00 Iris (Rec 18)
    {
      id: "18",
      recordNo: "M-2026-025",
      date: "2026/01/06 12:00",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petId: "1",
      petName: "Iris(イリス)",
      species: "犬",
      chiefComplaint: "入院手続き",
      doctor: "医師B",
      status: "作成中",
    },
    // 12:15 Rocky (Rec 16)
    {
      id: "16",
      recordNo: "M-2026-026",
      date: "2026/01/06 12:15",
      ownerId: "o8",
      ownerName: "中村 勇気",
      petId: "p10",
      petName: "ロッキー",
      species: "犬",
      chiefComplaint: "トリミング予約",
      doctor: "スタッフB",
      status: "作成中",
    },
    // 12:30 Luna (Rec 19)
    {
      id: "19",
      recordNo: "M-2026-027",
      date: "2026/01/06 12:30",
      ownerId: "o9",
      ownerName: "加藤 恵",
      petId: "p11",
      petName: "ルナ",
      species: "猫",
      chiefComplaint: "入院予約",
      doctor: "医師A",
      status: "作成中",
    },
    // 15:00 Choco (Rec 23)
    {
      id: "23",
      recordNo: "M-2026-028",
      date: "2026/01/06 15:00",
      ownerId: "o4",
      ownerName: "田中 美咲",
      petId: "p6",
      petName: "チョコ",
      species: "犬",
      chiefComplaint: "トリミング（受付）",
      doctor: "スタッフA",
      status: "作成中",
    },
  ];

export const MOCK_HOSPITALIZATIONS: Hospitalization[] = [
    {
      id: "1",
      hospitalizationNo: "H-2025-001",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      species: "犬",
      hospitalizationType: "入院",
      startDate: "2025/10/10",
      endDate: "2025/10/20",
      status: "入院中",
      cageId: "c1",
    },
    {
      id: "2",
      hospitalizationNo: "H-2025-002",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petName: "ミケ",
      species: "猫",
      hospitalizationType: "ホテル",
      startDate: "2025/10/08",
      endDate: "2025/10/15",
      status: "入院中",
      cageId: "c6",
    },
    {
      id: "3",
      hospitalizationNo: "H-2025-003",
      ownerName: "山本 健太",
      petName: "ポチ",
      species: "犬",
      hospitalizationType: "入院",
      startDate: "2025/09/20",
      endDate: "2025/09/30",
      status: "退院済",
    },
    {
      id: "4",
      hospitalizationNo: "H-2025-004",
      ownerName: "田中 美咲",
      petName: "チョコ",
      species: "犬",
      hospitalizationType: "ホテル",
      startDate: "2025/10/25",
      endDate: "2025/10/30",
      status: "予約",
    },
    {
      id: "5",
      hospitalizationNo: "H-2026-001",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      species: "犬",
      hospitalizationType: "入院",
      startDate: "2026/01/06",
      endDate: "2026/01/10",
      status: "予約",
    },
    {
      id: "6",
      hospitalizationNo: "H-2026-002",
      ownerName: "加藤 恵",
      petName: "ルナ",
      species: "猫",
      hospitalizationType: "入院",
      startDate: "2026/01/06",
      endDate: "2026/01/13",
      status: "予約",
    },
  ];

export const MOCK_PETS: Pet[] = [
    {
      id: "1",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      phone: "090-1111-2222",
      petNumber: "30042-008",
      name: "Iris(イリス)",
      status: "生存",
      species: "犬",
      birthDate: "2015/04/14",
      weight: "26.5kg",
      environment: "室内(散歩する)",
      lastVisit: "2015/08/28",
    },
    {
      id: "2",
      ownerId: "30042",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      phone: "090-1111-2222",
      petNumber: "30042-009",
      name: "Max(マックス)",
      status: "生存",
      species: "犬",
      birthDate: "2018/06/20",
      weight: "15.2kg",
      environment: "室内(散歩する)",
      lastVisit: "2024/11/15",
    },
    {
      id: "3",
      ownerId: "30043",
      ownerName: "田中　花子(タナカ　ハナコ)",
      phone: "080-3333-4444",
      petNumber: "30043-001",
      name: "ミケ",
      status: "生存",
      species: "猫",
      birthDate: "2020/03/10",
      weight: "4.2kg",
      environment: "室内",
      lastVisit: "2024/11/18",
    },
    // Simple pets for reservation mock
    { id: "p4", ownerId: "o3", ownerName: "鈴木 一郎", phone: "070-5555-6666", name: "タロウ", species: "犬" },
    { id: "p5", ownerId: "o3", ownerName: "鈴木 一郎", phone: "070-5555-6666", name: "ジロウ", species: "犬" },
    { id: "p6", ownerId: "o4", ownerName: "田中 美咲", phone: "090-9999-8888", name: "チョコ", species: "犬" },
    { id: "p7", ownerId: "o5", ownerName: "佐藤 花子", phone: "080-3333-4444", name: "レオ", species: "猫" },
    { id: "p8", ownerId: "o6", ownerName: "伊藤 次郎", phone: "090-1234-5678", name: "ハチ", species: "犬" },
    { id: "p9", ownerId: "o7", ownerName: "小林 さくら", phone: "080-9876-5432", name: "モモ", species: "猫" },
    { id: "p10", ownerId: "o8", ownerName: "中村 勇気", phone: "090-1122-3344", name: "ロッキー", species: "犬" },
    { id: "p11", ownerId: "o9", ownerName: "加藤 恵", phone: "080-5566-7788", name: "ルナ", species: "猫" },
    { id: "p12", ownerId: "o10", ownerName: "山田 太郎", phone: "090-2233-4455", name: "ケン", species: "犬" },
    { id: "p13", ownerId: "o11", ownerName: "高橋 由美", phone: "080-6677-8899", name: "ソラ", species: "猫" },
    { id: "p14", ownerId: "o12", ownerName: "松本 隆", phone: "090-3344-5566", name: "ゴン", species: "犬" },
    { id: "p15", ownerId: "o13", ownerName: "吉田 誠", phone: "080-7788-9900", name: "シロ", species: "犬" },
    { id: "p16", ownerId: "o14", ownerName: "井上 京子", phone: "090-4455-6677", name: "トラ", species: "猫" },
    { id: "p17", ownerId: "o15", ownerName: "木村 拓也", phone: "080-8899-0011", name: "ベロ", species: "犬" },
    { id: "p18", ownerId: "o16", ownerName: "佐々木 亮", phone: "090-5566-7788", name: "チビ", species: "猫" },
    { id: "p19", ownerId: "o17", ownerName: "山本 健太", phone: "090-1234-9876", name: "ポチ", species: "犬" },
];

export const generateMockAppointments = (): ReservationAppointment[] => {
    const appointments: ReservationAppointment[] = [];
    const baseDate = new Date(); // Current date (2026-01-02)
    const currentYear = baseDate.getFullYear();
    
    const doctors = ["医師A", "医師B", "スタッフA", "スタッフB"];
    const types: ReservationAppointment['type'][] = ["treatment", "checkup", "surgery", "trimming", "vaccine"];
    
    // Target period: Jan 1 to Jan 7 of the current year
    // Note: Month is 0-indexed (0 = Jan)
    const startDate = new Date(currentYear, 0, 1); 
    
    // Generate appointments for 7 days (Jan 1 - Jan 7)
    for (let i = 0; i < 7; i++) {
        const targetDate = new Date(startDate);
        targetDate.setDate(startDate.getDate() + i);
        
        // Generate 7-8 appointments per day to reach ~50 total (7 * 7.2 = ~50)
        const dailyCount = 7 + (Math.random() > 0.5 ? 1 : 0);

        for (let k = 0; k < dailyCount; k++) {
            // Random start time: 9:00 to 17:30 (to ensure even 2h appointments end by 19:30/20:00)
            // Hours: 9 to 17
            const hour = 9 + Math.floor(Math.random() * 9); 
            const minute = Math.random() > 0.5 ? 0 : 30;
            
            const start = new Date(targetDate);
            start.setHours(hour, minute, 0, 0);
            
            // Duration: 30, 60, 90, 120 mins
            // 1..4 * 30
            const durationSteps = 1 + Math.floor(Math.random() * 4);
            const duration = durationSteps * 30;
            
            const end = new Date(start.getTime() + duration * 60000);
            
            const pet = MOCK_PETS[Math.floor(Math.random() * MOCK_PETS.length)];
            
            appointments.push({
                id: `mock-2026-${i}-${k}`,
                start,
                end,
                ownerName: pet.ownerName,
                petName: pet.name,
                visitType: Math.random() > 0.3 ? "revisit" : "first",
                type: types[Math.floor(Math.random() * types.length)],
                doctor: doctors[Math.floor(Math.random() * doctors.length)],
                isDesignated: Math.random() > 0.7,
                status: "confirmed",
                petId: pet.id
            });
        }
    }

    return appointments;
  };

export const MOCK_TRIMMING_RECORDS: TrimmingRecord[] = [
    {
      id: "1",
      date: "2025/10/10",
      petNumber: "30042-008",
      petName: "Iris(イリス)",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      species: "犬",
      weight: "26.5kg",
      styleRequest: "サマーカット希望",
      staff: "スタッフA",
      status: "完了",
    },
    {
      id: "2",
      date: "2025/10/15",
      petNumber: "30042-009",
      petName: "Max(マックス)",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      species: "犬",
      weight: "15.2kg",
      styleRequest: "ふんわりカット",
      staff: "スタッフB",
      status: "予約",
    },
    {
      id: "3",
      date: "2025/10/12",
      petNumber: "30043-001",
      petName: "ミケ",
      ownerName: "田中　花子(タナカ　ハナコ)",
      species: "猫",
      weight: "4.2kg",
      styleRequest: "毛玉カット",
      staff: "スタッフA",
      status: "進行中",
    },
    {
      id: "4",
      date: "2026/01/06",
      petNumber: "p6",
      petName: "チョコ",
      ownerName: "田中 美咲",
      species: "犬",
      weight: "6.5kg",
      styleRequest: "シャンプーコース",
      staff: "スタッフA",
      status: "完了",
    },
    {
      id: "5",
      date: "2026/01/06",
      petNumber: "p17",
      petName: "ベロ",
      ownerName: "木村 拓也",
      species: "犬",
      weight: "12.0kg",
      styleRequest: "全体カット",
      staff: "スタッフB",
      status: "完了",
    },
    {
      id: "6",
      date: "2026/01/06",
      petNumber: "p10",
      petName: "ロッキー",
      ownerName: "中村 勇気",
      species: "犬",
      weight: "8.0kg",
      styleRequest: "爪切りのみ",
      staff: "スタッフB",
      status: "予約",
    },
    {
      id: "7",
      date: "2026/01/06",
      petNumber: "p8",
      petName: "シロ",
      ownerName: "吉田 誠",
      species: "犬",
      weight: "5.0kg",
      styleRequest: "シャンプー",
      staff: "スタッフA",
      status: "完了",
    },
    {
      id: "8",
      date: "2026/01/06",
      petNumber: "p6",
      petName: "チョコ",
      ownerName: "田中 美咲",
      species: "犬",
      weight: "6.5kg",
      styleRequest: "トリミング",
      staff: "スタッフA",
      status: "予約",
    },
  ];

export const MOCK_EXAMINATION_RECORDS: ExaminationRecord[] = [
    {
      id: "1",
      date: "2025/10/10 10:15",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      testType: "血液検査",
      doctor: "医師A",
      status: "完了",
      resultSummary: "WBC正常, RBC正常",
    },
    {
      id: "2",
      date: "2025/10/10 11:30",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petName: "ミケ",
      testType: "生化学検査",
      doctor: "医師B",
      status: "完了",
      resultSummary: "異常なし",
    },
    {
      id: "3",
      date: "2025/10/09 15:20",
      ownerName: "山本 健太",
      petName: "ポチ",
      testType: "超音波",
      doctor: "医師A",
      status: "依頼中",
    },
    {
      id: "4",
      date: "2026/01/06 10:05",
      ownerName: "井上 京子",
      petName: "トラ",
      testType: "血液検査",
      doctor: "医師C",
      status: "完了",
      resultSummary: "WBC軽度上昇, CRP正常",
    },
    {
      id: "5",
      date: "2026/01/06 11:15",
      ownerName: "高橋 健一",
      petName: "ケン",
      testType: "フィラリア検査",
      doctor: "医師B",
      status: "検査中",
    },
    {
      id: "6",
      date: "2026/01/06 11:30",
      ownerName: "伊藤 翼",
      petName: "ソラ",
      testType: "一般身体検査",
      doctor: "医師C",
      status: "検査中",
    },
  ];

export const MOCK_ACCOUNTING_RECORDS: AccountingRecord[] = [
    {
      id: "1",
      date: "2025/10/10 10:45",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      amount: 15400,
      method: "-",
      status: "未収",
      note: "本日診療分",
    },
    {
      id: "2",
      date: "2025/10/10 11:30",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petName: "ミケ",
      amount: 5500,
      method: "現金",
      status: "回収済",
    },
    {
      id: "3",
      date: "2025/10/09 15:20",
      ownerName: "山本 健太",
      petName: "ポチ",
      amount: 32000,
      method: "クレジットカード",
      status: "回収済",
    },
    // New Records for Dashboard Consistency (2026/01/06)
    {
      id: "4",
      date: "2026/01/06 09:45",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      amount: 15400,
      method: "-",
      status: "未収",
      note: "本日診療分",
    },
    {
      id: "5",
      date: "2026/01/06 09:50",
      ownerName: "田中　花子(タナカ　ハナコ)",
      petName: "ミケ",
      amount: 8800,
      method: "-",
      status: "未収",
      note: "ワクチン接種",
    },
    {
      id: "6",
      date: "2026/01/06 09:30",
      ownerName: "田中 美咲",
      petName: "チョコ",
      amount: 6600,
      method: "-",
      status: "未収",
      note: "トリミング",
    },
    {
      id: "7",
      date: "2026/01/06 09:55",
      ownerName: "吉田 誠",
      petName: "シロ",
      amount: 4400,
      method: "-",
      status: "未収",
      note: "定期検診",
    },
    {
      id: "8",
      date: "2026/01/06 10:05",
      ownerName: "井上 京子",
      petName: "トラ",
      amount: 12000,
      method: "-",
      status: "未収",
      note: "血液検査",
    },
    {
      id: "9",
      date: "2026/01/06 11:40",
      ownerName: "木村 拓也",
      petName: "ベロ",
      amount: 5500,
      method: "-",
      status: "未収",
      note: "爪切り・耳掃除",
    },
    {
      id: "10",
      date: "2026/01/06 09:00",
      ownerName: "林　文明(ハヤシ　フミアキ)",
      petName: "Iris(イリス)",
      amount: 3300,
      method: "現金",
      status: "回収済",
      note: "再診料",
    },
    {
      id: "11",
      date: "2026/01/06 09:15",
      ownerName: "佐々木 亮",
      petName: "チビ",
      amount: 7700,
      method: "クレジットカード",
      status: "回収済",
      note: "ワクチン",
    },
  ];

export const MOCK_VACCINATION_RECORDS: VaccinationRecord[] = [
    { id: "1", ownerName: "林 文明", petName: "Iris", vaccineName: "��犬病ワクチン", date: "2025/10/10", nextDate: "2026/10/10" },
    { id: "2", ownerName: "田中　花子", petName: "ミケ", vaccineName: "3種���合ワクチン", date: "2025/09/15", nextDate: "2026/09/15" },
    { id: "3", ownerName: "山本 健太", petName: "ポチ", vaccineName: "フィラリア予防", date: "2025/08/20", nextDate: "2025/09/20" },
    { id: "4", ownerName: "鈴��� 一郎", petName: "タロウ", vaccineName: "ノミダニ予防", date: "2025/08/22", nextDate: "2025/09/22" },
    { id: "5", ownerName: "佐々木 亮", petName: "チビ", vaccineName: "3種混合ワクチン", date: "2026/01/06", nextDate: "2027/01/06" },
    // Leo: Last year's record, making him due today
    { id: "6", ownerName: "佐藤 花子", petName: "レオ", vaccineName: "猫ウイルス性鼻気管炎", date: "2025/01/06", nextDate: "2026/01/06" },
    // Mike: Today's new record
    { id: "7", ownerName: "田中　花子", petName: "ミケ", vaccineName: "3種混合ワクチン", date: "2026/01/06", nextDate: "2027/01/06" },
  ];